### ISSUE TITLE
gplus:groovydoc allow using custom gstringTemplate with groovydoc mojo

### ISSUE THREAD

**Issue by majusmisiak** [groovy/GMavenPlus#105]
Hi,

Would it be possible to make `classpath` configurable for this plugin, so that custom gstringTemplate could be used instead of default one packaged with plugin? 

This feature seems to be available in Gradle, but I wasn't able to get it working with Maven only:

- http://mrhaki.blogspot.com/2016/01/groovy-goodness-customise-groovydoc.html 
- https://docs.gradle.org/current/dsl/org.gradle.api.tasks.javadoc.Groovydoc.html

**Comment by keeganwitt** [comment]
Hmm... I think I'd have to have a way of injecting classes at runtime onto the plugin classpath to do it the same way Gradle did.  I'll have to play with it to see what's possible.

**Comment by keeganwitt** [comment]
Now that we have the `includeClasspath` argument, you can add the templates to the project classpath, or use `PROJECT_AND_PLUGIN` to add them as a dependency in the plugin.  I'll add array parameters to allow these to be specified.

**Comment by keeganwitt** [comment]
Here's an example of the configuration that provides the same classes as the default in the current Groovy

```xml
<defaultDocTemplates>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/index.html</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/overview-frame.html</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/allclasses-frame.html</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/overview-summary.html</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/help-doc.html</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/index-all.html</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/deprecated-list.html</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/stylesheet.css</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/topLevel/inherit.gif</param>
    <param>org/apache/groovy/docgenerator/groovy.ico</param>
</defaultDocTemplates>
<defaultPackageTemplates>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/packageLevel/package-frame.html</param>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/packageLevel/package-summary.html</param>
</defaultPackageTemplates>
<defaultClassTemplates>
    <param>org/codehaus/groovy/tools/groovydoc/gstringTemplates/classLevel/classDocName.html</param>
</defaultClassTemplates>
```
