### ISSUE TITLE
Add Java 11 support

### ISSUE THREAD

**Issue by vimal4david** [groovy/GMavenPlus#106]
I am getting below [error](https://travis-ci.org/spotbugs/spotbugs-maven-plugin/jobs/429572630) when I use the plugin with Java 11

```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:generateStubs (compileGroovy) on project spotbugs-maven-plugin: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: startup failed:
[ERROR] General error during conversion: java.lang.UnsupportedOperationException
[ERROR]
[ERROR] java.lang.UnsupportedOperationException
[ERROR] 	at groovyjarjarasm.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:651)
[ERROR] 	at groovyjarjarasm.asm.ClassReader.accept(ClassReader.java:391)
```

**Comment by vimal4david** [comment]
Relates to Groovy [issue](https://issues.apache.org/jira/browse/GROOVY-8727).

**Comment by vimal4david** [comment]
Pull request is [here](https://github.com/groovy/GMavenPlus/pull/107)

**Comment by hazendaz** [comment]
Anyone know what the holdup is here?  Sounds trivial enough to get this out.  Doesn't sound like the PR will solve the issue though and I don't think it's tied to groovy 2.5.3 as 2.5.2 supports jdk11 last I checked unless I'm missing something.  This issue is holding up having maven support for spotbugs for jdk11 which many are continually asking about.

**Comment by keeganwitt** [comment]
2.5.2 support of JDK 11 was incomplete, it was missing the stuff I added here https://github.com/apache/groovy/commit/b9f85fd32da7b06c1b8a35d176911da40c762e33.  The GMavenPlus changes needed to accommodate that are pretty straight-forward, I should be able to get that wrapped up this weekend, but you'll still be waiting on a new Groovy release.

**Comment by hazendaz** [comment]
Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by keeganwitt** [comment]
I pushed the fix.  I'll release a new version of GMavenPlus once the new Groovy version is released.
https://github.com/groovy/GMavenPlus/commit/af57fa20b62409397b391d36a3f257a6985ea4fa

**Comment by rmannibucau** [comment]
I wonder if it does not also show that the compilationConfiguration can't be customized (typically asmResolving=false and classLoaderResolving=false). Not the exact same issue but would be a workaround.
