### ISSUE TITLE
Snapshot version of 1.6.2 is not available

### ISSUE THREAD

**Issue by zarebski-m** [groovy/GMavenPlus#108]
As I understand, you are going to release 1.6.2 after Groovy 2.5.3 is officially released. There is a snapshot version of Groovy available though: https://oss.jfrog.org/artifactory/oss-snapshot-local/org/codehaus/groovy/groovy-all/2.5.3-SNAPSHOT/

Could GMavenPlus 1.6.2-SNAPSHOT be published as well? Or is there a repository where it is available? I looked at https://oss.jfrog.org/artifactory/plugins-snapshot/org/codehaus/gmavenplus/gmavenplus-plugin/, but there is no snapshot of 1.6.2.

**Comment by keeganwitt** [comment]
I have uploaded a snapshot of 1.6.2: https://oss.sonatype.org/content/repositories/snapshots/org/codehaus/gmavenplus/gmavenplus-plugin/1.6.2-SNAPSHOT/.
