### ISSUE TITLE
Could not find goal 'testCompile' in plugin org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1

### ISSUE THREAD

**Issue by mirabilos** [groovy/GMavenPlus#109]
Probably the same thing as https://github.com/groovy/GMavenPlus/issues/84 but in 1.6.1… (upgrading from, incidentally, 1.5, since I’m reviewing all plugins for updates at the moment)

[ERROR] Could not find goal 'testCompile' in plugin org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1 among available goals addSources, addStubSources, addTestSources, addTestStubSources, compile, compileTests, console, execute, generateStubs, generateTestStubs, groovydoc, groovydocTests, help, removeStubs, removeTestStubs, shell -> [Help 1]

This is in an internal/proprietary codebase, though. I’ll see whether any OSS projects of ours are also affected.

**Comment by mirabilos** [comment]
OK, I also got it in an OSS project:

https://evolvis.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=veraweb/veraweb.git;a=tree;h=refs/heads/gmavenplus161-bug;hb=refs/heads/gmavenplus161-bug

    git clone -b gmavenplus161-bug https://evolvis.org/anonscm/git/veraweb/veraweb.git

Tail of build log:

    […]
    [INFO] ------------------< org.evolvis.veraweb:veraweb-core >------------------
    [INFO] Building veraweb-core 1.9.4-SNAPSHOT                             [15/17]
    [INFO] --------------------------------[ war ]---------------------------------
    [INFO] ------------------------------------------------------------------------
    [INFO] Reactor Summary:
    [INFO]
    [INFO] org.evolvis.veraweb (parent) 1.9.4-SNAPSHOT ........ SUCCESS [01:13 min]
    [INFO] org.evolvis.veraweb:middleware (parent) ............ SUCCESS [  5.542 s]
    [INFO] org.evolvis.veraweb:middleware:octopus (parent) .... SUCCESS [  4.123 s]
    [INFO] OCTOPUS rpctunnel .................................. SUCCESS [  7.042 s]
    [INFO] OCTOPUS core ....................................... SUCCESS [ 22.005 s]
    [INFO] OCTOPUS annotation extension ....................... SUCCESS [  5.372 s]
    [INFO] veraweb-middleware:tarent-commons .................. SUCCESS [ 16.527 s]
    [INFO] OCTOPUS common extension ........................... SUCCESS [  8.175 s]
    [INFO] OCTOPUS cronjob extension .......................... SUCCESS [  6.165 s]
    [INFO] OCTOPUS jmx extension .............................. SUCCESS [  5.632 s]
    [INFO] OCTOPUS servlet .................................... SUCCESS [  5.488 s]
    [INFO] veraweb-middleware:tarent-database ................. SUCCESS [ 11.408 s]
    [INFO] OCTOPUS bean extension ............................. SUCCESS [  9.694 s]
    [INFO] rest-api-common .................................... SUCCESS [ 11.798 s]
    [INFO] veraweb-core ....................................... FAILURE [  0.010 s]
    [INFO] veraweb-export ..................................... SKIPPED
    [INFO] rest-api 1.9.4-SNAPSHOT ............................ SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 03:13 min
    [INFO] Finished at: 2018-10-05T16:13:14+02:00
    [INFO] ------------------------------------------------------------------------
    [ERROR] Could not find goal 'testCompile' in plugin org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1 among available goals addSources, addStubSources, addTestSources, addTestStubSources, compile, compileTests, console, execute, generateStubs, generateTestStubs, groovydoc, groovydocTests, help, removeStubs, removeTestStubs, shell -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException

**Comment by keeganwitt** [comment]
The goal is named "compileTests" -- it was necessary to change some goal names a while back so that they registered properly in IntelliJ.

**Comment by mirabilos** [comment]
Thanks, that fixed it!

https://evolvis.org/plugins/scmgit/cgi-bin/gitweb.cgi?p=tartools/mvnparent.git;a=commitdiff;h=32a152d07ea0eb1882830b896921f5f5d3779365;hp=1466f60197fa3915511702e73c44857abe5b06f5
