### ISSUE TITLE
Stub re-declares abstract methods from traits

### ISSUE THREAD

**Issue by chrylis** [groovy/GMavenPlus#111]
I have a trait that declares an abstract method `MockMvc getMockMvc`. This is satisfied because my test class inherits from a base `MockMvcSpec` which provides the property. In my generated stub, both the `extends` and `implements` clauses are provided correctly.

However, the stub re-declares `public abstract MockMvc getMockMvc`, which causes the Java compiler to fail because it's re-abstracting the method whose implementation should be inherited.

**Comment by keeganwitt** [comment]
To be clear, this is the case you are describing?
```groovy
class Test extends MockMvcSpec implements MockMvc { }

trait MockMvc {
  def abstract getMockMvc()
}

class MockMvcSpec {
  def mockMvc
}
```

**Comment by chrylis** [comment]
Close, but a bit more detail is probably clearer:

```
trait HasMockMvc {
  abstract MockMvc getMockMvc()
}

class MockMvcSpec {
  @Autowired
  MockMvc mockMvc // in my own case, typed in case that's relevant
}

class TestClass extends MockMvcSpec implements HasMockMvc { }
```

**Comment by keeganwitt** [comment]
GMavenPlus uses Groovy's stub generation code, and it looks like you've found an issue with it.  I've opened an issue for this: https://issues.apache.org/jira/browse/GROOVY-8895

**Comment by keeganwitt** [comment]
Closing, as there's an open issue against Groovy for this.
