### ISSUE TITLE
Log which class triggered errors in mojos

### ISSUE THREAD

**Issue by chrylis** [groovy/GMavenPlus#112]
I'm trying to upgrade from 1.6.1 to 1.6.2, and I'm running into "Unable to get a Groovy class from classpath." in the `groovydoc` goal. I suspect this is something to do with the modularization in 2.5 and it just wants a particular module I don't already have, but the error message would be much more helpful if it included _which_ class produced the `ClassNotFoundException`.

I am making some progress with `-X` on my development machine, but this first cropped up in CI, where all I have is the standard log.

cf https://github.com/groovy/GMavenPlus/blob/12926110c09bc736ce2bab87bd209801b676dfa8/src/main/java/org/codehaus/gmavenplus/mojo/GroovyDocMojo.java#L54

**Comment by keeganwitt** [comment]
Sorry for the late reply.  I'd need to see some of your pom to figure out what's going on here. The stacktrace should already log the class it can't find.  I'm not sure an easy way to parse the stacktrace to include the class in the regular exception message.

**Comment by chrylis** [comment]
In this particular case, the log message is in the catch block for `ClassNotFoundException e`; the missing class is (in practice although not required by API contract) listed in `e.message`.

**Comment by keeganwitt** [comment]
OK. I've added a change to log the message from the original exception.
