### ISSUE TITLE
Replace google collections dependency with guava

### ISSUE THREAD

**Issue by gludington** [groovy/GMavenPlus#114]
gmavenplus depends on google collections, which has been deprecated and its contents moved to guava several years ago.  If trying to execute a script in a maven build whose libraries depends on any subsequent changes - in our case, the ImmutableSet class -- the build fails with an InvocationTargetException.  Since maven does not allow you to exclude the direct dependencies of a plugin, there does not appear to be any workaround.

**Comment by keeganwitt** [comment]
Update: I removed the Plexus Default Container dependency and my test suite still passed -- it looks like I can drop that out to avoid this issue.

**Comment by gludington** [comment]
When I added guava as an explicit dependency, it displaced the one from the plexus install, so that is a workaround as well.
`      <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.6.2</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                        <configuration>
                            <scripts>
                                <script>
                                    ...snipped for brevity...
                                </script>
                            </scripts>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-all</artifactId>
                        
                        <version>2.4.15</version>
                        <scope>runtime</scope>
                    </dependency>
                    <dependency>
                        <groupId>com.google.guava</groupId>
                        <artifactId>guava</artifactId>
                        <version>26.0-jre</version>
                    </dependency>
                </dependencies>
            </plugin>`

**Comment by keeganwitt** [comment]
Only console, shell, and execute Mojos combine the project and plugin classpaths.  This won't affect the other goals.  But glad you have a workaround for now.
