### ISSUE TITLE
Unexpected token while trying to compile the java code 

### ISSUE THREAD

**Issue by suneelkumar45** [groovy/GMavenPlus#118]
Not sure this is anyone tried before or not. started working on a project which has combination of frameworks spring-boot+ Maven + groovy + jooq . In project jooq table creation takes minimum 5 mins every time when execute command mvn clean install. so decided very first time will create the jooq tables and from next time on wards will skip the generating sources. so used <skip>${jooq.codegen.skip}</skip> flag to skip the code generation.

Issue  with gmaven plus plugin while trying to generate project sources very first time compiling the sources I get error unexpected token when it tries to compile the value with double quotes line. sample below.
How to resolve this error? 

[INFO] --- gmavenplus-plugin:1.6.1:compile (compile) @ ***---
[INFO] Using Groovy 2.4.15 to perform compile.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:20 min
[INFO] Finished at: 2018-12-18T14:43:53+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6.1:compile (compile) on project ***: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: startup failed:
[ERROR] target\generated-sources\jooq-postgres\com\**\**\jooq\**\Sequences.java: 18: unexpected token: http://www.jooq.org @ line 18, column 9.
[ERROR]            "http://www.jooq.org",
[ERROR]            ^
[ERROR]
[ERROR] 1 error

code -snippet :

@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
This is My pom.xml configuration . any help is appreciated.

<executions>
  <execution>
     <id>generate-sources</id>
      <phase>generate-sources</phase>
      <goals>
         <goal>generate</goal>
       </goals>
    </execution>
 </executions>
<configuration>
  <skip>${jooq.codegen.skip}</skip>
 </configuration>

gmaven plus plugin config :

<plugins>
            
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>${gmavenplus.plugin.version}</version>
                <executions>
                    <execution>
                    	<id>add-sources</id>
                        <goals>
                        	<goal>addSources</goal>
                        	<goal>addTestSources</goal>
                        </goals>
                    </execution>
                    <execution>
                    	<id>compile</id>
                    	<goals>
                    		<goal>compile</goal>
                    	</goals>
                    </execution>
                    <execution>
                    	<id>compile-tests</id>
                    	<goals>
                    		<goal>compileTests</goal>
                    	</goals>
                    </execution>
                </executions>
                <configuration>
                	<sources>
                		<source>
                			<directory>target/generated-sources/jooq-postgres</directory>
                		</source>
                	</sources>
                	<testSources>
                		<testSource>
                			<directory>target/generated-sources/jooq-postgres</directory>
                		</testSource>
                	</testSources>
                </configuration>
            </plugin>

Thanks,
Suneel

**Comment by keeganwitt** [comment]
The POM XML got its formatting stripped when you pasted.  Are you putting the generated jooq Java sources into the Groovy sources?  It looks like that's what's happening.  If so, that's the problem; the generated Java is not valid Groovy (some Java is, but not all).

**Comment by suneelkumar45** [comment]
Yes ...Jooq java generator ...generates the java code and annotates with @generated and @SuppressWarnings for each class. there is option in jooq to trun-off  generated annotation but not the supresswarnings. I suspect Groovy is complaining about the double quotes. is there a way can tell gmaven compiler not to do the strict validation?

**Comment by keeganwitt** [comment]
I think I'd try adding an exclusion to the sources configured to be compiled (the normal Maven FileSet way).  GmavenPlus isn't explicitly doing any validation -- it's just calling the Groovy compilation classes.

**Comment by keeganwitt** [comment]
I think there's nothing further needed from my end, so I'm closing for now.  We can re-open if needed.
