### ISSUE TITLE
Bring back logging of executed scripts (path or URL)

### ISSUE THREAD

**Issue by jbliznak** [groovy/GMavenPlus#119]
Before https://github.com/groovy/GMavenPlus/issues/36 URLs to scripts processed were logged during execution of plugin like this:
```
<plugin>
    <groupId>org.codehaus.gmavenplus</groupId>
    <artifactId>gmavenplus-plugin</artifactId>
    <executions>
        <execution>
            <id>my-execution</id>
            <phase>pre-integration-test</phase>
            <goals><goal>execute</goal></goals>
            <configuration>
                <scripts><script>file:///${basedir}/src/test/scripts/my-script${variant}${specific.suffix}.groovy</script></scripts>
            </configuration>
        </execution>
    </executions>
</plugin>
```

```
[INFO] --- gmavenplus-plugin:1.5:execute (my-execution) @ my-project ---
[INFO] Using Groovy 2.4.15 to perform execute.
[INFO] Fetching Groovy script from file:////tmp/my-project/src/test/scripts/my-script.groovy.
```
This was removed by changes in https://github.com/groovy/GMavenPlus/commit/6e61c6483ca4dc210a37707eb3bbe8941e4805bc#diff-e2fc100a5ec1d6e73ee84a32f9d09bc5L183 and now you can only see this:
```
[INFO] --- gmavenplus-plugin:1.6.2:execute (my-execution) @ my-project ---
[INFO] Using Groovy 2.4.15 to perform execute.
```

Please consider bringing back this logging.
That way you have overview of used scripts, quite useful when the paths/URLs to them are parametrized so you know for sure what variant was used.

**Comment by keeganwitt** [comment]
Makes sense.  I's been a few years since I made this [change](https://github.com/groovy/GMavenPlus/issues/36).  I think I removed the logging because "fetching" was kinda confusing because the URL could be local or remote.  But I think I'll just change "Fetching" to "Running" and bring it back as you've suggested.  Thanks for the feedback!
