### ISSUE TITLE
Use unique configuration names for every mojo, so goals don't conflict

### ISSUE THREAD

**Issue by keeganwitt** [groovy/GMavenPlus#120]
#31/#58 introduced a breaking change to `testStubsOutputDirectory` and `stubsOutputDirectory`.  In addition to fixing this, we should ensure there are no other conflicts.

**Comment by keeganwitt** [comment]
This is labeled a bug because #31/#58 introduced a breaking change to `testStubsOutputDirectory` and `stubsOutputDirectory`, which is one of the conflicts.

**Comment by keeganwitt** [comment]
Here's the current configuration options from the latest snapshot.

  | addSources | addStubSources | addTestSources | addTestStubSources | compile | compileTests | console | execute | generateStubs | generateTestStubs | groovydoc | groovydocTests | removeStubs | removeTestStubs | shell
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
allowSystemExits |   |   |   |   |   |   | X | X |   |   |   |   |   |   | X
bindPropertiesToSeparateVariables |   |   |   |   |   |   | X | X |   |   |   |   |   |   | X
configScript |   |   |   |   | X | X |   |   |   |   |   |   |   |   |  
continueExecuting |   |   |   |   |   |   |   | X |   |   |   |   |   |   |  
debug |   |   |   |   | X | X |   |   | X | X |   |   |   |   |  
displayAuthor |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
docTitle |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
footer |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
groovyDocOutputDirectory |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
grovyDocJavaSources |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
header |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
invokeDynamic |   |   |   |   | X | X |   |   |   |   |   |   |   |   |  
links |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
outputDirectory |   | X |   | X | X | X |   |   | X | X |   |   | X | X |  
overviewFile |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
parameters |   |   |   |   | X | X |   |   |   |   |   |   |   |   |  
properties |   |   |   |   |   |   | X | X |   |   |   |   |   |   | X
scope |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
skipGroovyDoc |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
skipTests | X | X | X | X | X | X |   |   | X | X | X | X | X | X |  
sourceEncoding |   |   |   |   | X | X |   | X | X | X |   |   |   |   |  
sources | X | X | X | X | X | X |   |   | X | X | X | X | X | X |  
stylesheetEncoding |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
stylesheetFile |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
targetBytecode |   |   |   |   | X | X |   |   | X | X |   |   |   |   |  
testGroovyDocOutputDirectory |   |   |   |   |   |   |   |   |   |   | X | X |   |   |  
testSources | X | X | X | X | X | X |   |   | X | X | X | X | X | X |  
tolerance |   |   |   |   | X | X |   |   | X | X |   |   |   |   |  
useSharedClassLoader | X | X | X | X | X | X | X | X | X | X | X | X | X | X | X
verbose |   |   |   |   | X | X |   |   | X | X |   |   |   |   |  
verbosity |   |   |   |   |   |   |   |   |   |   |   |   |   |   | X
warningLevel |   |   |   |   | X | X |   |   | X | X |   |   |   |   |  
windowTitle |   |   |   |   |   |   |   |   |   |   | X | X |   |   |

**Comment by keeganwitt** [comment]
The following changes have been done

  | 1.5 | 1.6 | 1.7
-- | -- | -- | --
gplus:addStubSources | stubsOutputDirectory | outputDirectory | stubsOutputDirectory
gplus:addTestStubSources | testStubsOutputDirectory | outputDirectory | testStubsOutputDirectory
gplus:compileTests/gplus:testCompile | testOutputDirectory | outputDirectory | testOutputDirectory
gplus:generateStubs | stubsOutputDirectory | outputDirectory | stubsOutputDirectory
gplus:generateTestStubs/gplus:testGenerateStubs | testStubsOutputDirectory | outputDirectory | testStubsOutputDirectory
gplus:groovydocTests/gplus:testGroovydoc | groovydocJavaSources | groovydocJavaSources | testGroovydocJavaSources
gplus:removeStubs | stubsOutputDirectory | outputDirectory | stubsOutputDirectory
gplus:removeTestStubs | testStubsOutputDirectory | outputDirectory | testStubsOutputDirectory

In addition, I removed parameters from goals which they don't apply to:
gplus:addSources
* skipTests
* testSources

gplus:addStubSources
* skipTests
* sources
* testSources

gplus:addTestSources
* outputDirectory
* skipTests
* sources

gplus:addTestStubSources
* skipTests
* sources
* testSources

gplus:compile
* skipTests
* testSources

gplus:compileTests
* sources

gplus:console
* skipTests

gplus:execute
* skipTests

gplus:generateStubs
* skipTests
* testSources

gplus:generateTestStubs
* sources

gplus:groovydoc
* skipTests
* testSources
* testGroovyDocOutputDirectory

gplus:groovydocTests
* skipTests
* sources

gplus:removeStubs
* skipTests
* sources
* testSources

gplus:removeTestStubs
* skipTests
* sources
* testSources

gplus:shell
* skipTests

**Comment by keeganwitt** [comment]
While I created `testGroovydocJavaSources`, since it is related to sources, I decided against creating separate test versions for all the parameters related to compilation.  This is to be consistent with [compile-mojo](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html) vs [testCompile-mojo](https://maven.apache.org/plugins/maven-compiler-plugin/testCompile-mojo.html) of Maven Compiler Plugin.

**Comment by drdamour** [comment]
cool look forward to the release!

**Comment by keeganwitt** [comment]
I apologize for the long turnaround. I've had a lack of free time lately, and I've been triple checking my changes (since they're breaking) to try to avoid having to make a future breaking change.
