### ISSUE TITLE
New goal for generating a JAR for apidocs

### ISSUE THREAD

**Issue by pmwmedia** [groovy/GMavenPlus#124]
I use the goal `groovydoc` for generating gapidocs.  That works great so far. However, I miss a goal for generating a JAR for apidocs.

For example, there is [doc-jar goal](http://davidb.github.io/scala-maven-plugin/example_doc.html) for Scala, and a [javadocJar goal](https://github.com/Kotlin/dokka) for Kotlin respectively. It would be nice to have one for Groovy, too!

**Comment by keeganwitt** [comment]
I'd originally planned on doing this if/when I was able to wrap the GroovyDoc stuff into a regular Maven site plugin.  But I could add a Mojo where I just use a plain old `JarOutputStream` to write a jar I suppose.
