### ISSUE TITLE
Doesn't work with Java 12 --enable-preview

### ISSUE THREAD

**Issue by krzyk** [groovy/GMavenPlus#125]
When I try to compile a project that has few java classes, few java test cases and few groovy test cases and `--enable-preview` is enabled (with Java 12) plugin fails with:
```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6.3:compileTests (default) on project apikey-manager-api: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: Preview features are not enabled for com/acme/config/EndToEndTest (class file version 56.65535). Try running with '--enable-preview' -> [Help 1]
```

When I disable plugin (and basically groovy tests), all java tests work correctly. 
How can I pass additional javac/java options (like `--enable-preview`) to groovyc with this plugin?

**Comment by keeganwitt** [comment]
Sorry, I haven't played with this much yet.  Are you trying to pass an argument to javac for compiling the stubs?  If you're talking about the Groovy file compilation, I don't think groovyc has that as an argument.  What would you expect it to even do?  The argument is talking about Java language features.

**Comment by krzyk** [comment]
Well, the issue is that with `--enable-preview` javac generates code with class file bytecode version`56.65535` (generally anything > 0 after the decimal, is considered *with preview*).
And later on any code that uses such `.class` files also have to have the bytecode version of `56.65535` (or greated, I think).

So, if I have a production code compiled with `--enable-preview`, also my test code has to be compiled this way. And I I have groovy code in tests that use production code (which is 100% cases I think ;) then this groovy code also has to be put into `.class` files that have bytecode version >= `56.65535`.


The above is my approximation from https://bugs.openjdk.java.net/browse/JDK-8195734:
In order to allow the runtime system to detect when "opt in" is necessary, compilers must emit class files which (i) memorialize the use of preview language features by the original source code, and (ii) record the use of preview VM features in the constant pool entries and attributes of the class files. In more detail:

    If Java source code uses a preview language feature of Java SE $N, then a Java compiler must record that the emitted class file depends on the preview VM features of Java SE $N. This applies even if the preview language feature is "syntactic sugar", i.e., it can be compiled without relying on preview VM features (such as novel class file constructs).

    If a compiler (Java or non-Java) emits a class file which uses a preview VM feature of Java SE $N, then the compiler must record that the emitted class file depends on the preview VM features of Java SE $N. For a Java compiler, this requirement applies even if the Java source code uses no preview language features, because a Java compiler may choose to implement a final and permanent language feature by translation to a preview VM feature.

**Comment by keeganwitt** [comment]
We'd need to add a new flag in Groovy's compiler code to do this.  I'm trying to find if [ASM](https://asm.ow2.io/) supports this.

**Comment by keeganwitt** [comment]
I opened this issue to track this work: https://issues.apache.org/jira/browse/GROOVY-9073

**Comment by keeganwitt** [comment]
Changes have been made to master (Groovy 3.x) and the GROOVY_2_5_X (Groovy 2.5.x) branches.  I can now make changes to GMavenPlus to leverage this new feature.
