### ISSUE TITLE
Setting a security manager is inherently not thread-safe

### ISSUE THREAD

**Issue by TobiX** [groovy/GMavenPlus#145]
The same issue came up with gmaven and they just ripped out the NoExitSecurityManager completly (https://github.com/groovy/gmaven/pull/8). I know there is an option for that (`allowSystemExits`), but it seems people fall over the issue regardless (for example #56).

I'd suggest to:
- Either follow gmaven's lead and get rid of that feature
- Or at least set `allowSystemExits` to `true` by default

(Another "solution" would probably be to create a singleton lock around https://github.com/groovy/GMavenPlus/blob/master/src/main/java/org/codehaus/gmavenplus/mojo/ExecuteMojo.java#L113-L139 and hope no other plugin plays around with the security manager in the mean time...)

**Comment by keeganwitt** [comment]
Good point. Thank you for bringing this up. I'm reluctant to remove the feature, as it seemed some users are using it. I'm also reluctant to introduce the lock, as it'd effectively make it single threaded. Setting it to true by default and putting a warning in the documentation seems appropriate though.

Unfortunately the version of the Maven API I'm targetting doesn't seem to support the ability to detect whether a thread configuration has been set, so I can't have GMavenPlus ignore the `allowSystemExits` in parallel builds or print a runtime warning, which I would have preferred to just a warning in the documentation.
