### ISSUE TITLE
groovydoc-jar has wrong extension when installed/deployed

### ISSUE THREAD

**Issue by jonenst** [groovy/GMavenPlus#151]
Hi,
the groovydoc-jar is installed in the .m2 or deployed to remote repositories with an extension  of "groovydoc":
```
 [INFO] Installing /tmp/aze/my-app/target/my-app-1.0-SNAPSHOT-groovydoc.jar to .m2/repository/my-app-1.0-SNAPSHOT-groovydoc.groovydoc
```

That's because it uses the type "groovydoc"
GroovyDocJarMojo.java:
```
projectHelper.attachArtifact(project, "groovydoc", classifier, outputFile); 
```
 and you don't provided an artifacthandler for this type.

`See https://maven.apache.org/ref/3.6.3/maven-core/artifact-handlers.html where javadoc type is correctly mapped to the ".jar" extension (in https://github.com/apache/maven/blob/master/maven-core/src/main/resources/META-INF/plexus/artifact-handlers.xml). If you wanted to to the same, you would have to add a component.xml and the plugin should be used with the "extension=true" parameter (as per this stackoverflow answer: https://stackoverflow.com/a/1427749 )

An alternative could be to simply use the "javadoc" type. That's what the scaladoc-maven-plugin does.   https://github.com/davidB/scala-maven-plugin/blob/da1784d364236ac1b55e68649539aee9197afc93/src/main/java/scala_maven/ScalaDocJarMojo.java#L138

Note that you could also set the classifier to javadoc by default, I think it would help most projects.. Again that's what scaladoc-maven-plugin does: https://github.com/davidB/scala-maven-plugin/blob/da1784d364236ac1b55e68649539aee9197afc93/src/main/java/scala_maven/ScalaDocJarMojo.java#L70

Cheers,
Jon

**Comment by keeganwitt** [comment]
My only concern with changing to javadoc classifier is if a project that had both Java and Groovy in it decided to produce both a javadoc and a groovydoc artifact.  I'll do some reading on the artifact handler, thank you for those links.

In the meantime, you can change the classifier with
```xml
<classifier>javadoc</classifier>
```

**Comment by jonenst** [comment]
Hi,
Thanks for your answers. I am indeed using classifier=javadoc, I was only suggesting this to simplify the plugin in general.

**Comment by keeganwitt** [comment]
I'm having trouble adding the artifact handler without also adding a custom package type and lifecycle (which is the only way I'd used the artifact handler in the past). I'm thinking now of making it "javadoc" type, so the default handler can parse it, but still change the classifier to "groovydoc".

Can you think of any downsides to this approach?

**Comment by jonenst** [comment]
Hi, this is a good approach. Keeping the groovydoc classifier has the benefit of beeing backwards compatible, even if it might not be the best default for most project. I think you can merge this

**Comment by keeganwitt** [comment]
I apologize for the delay, I forgot to open a PR and lost track of this.

**Comment by jonenst** [comment]
No problem, thanks for fixing this ! Also I think it's a good thing that in the end you chose the type "javadoc".
