### ISSUE TITLE
mvn site creation is missing groovy documentation 

### ISSUE THREAD

**Issue by Steffengreiner** [groovy/GMavenPlus#160]
Hi, 

I wrote a small project to test for the inclusion of groovy documentation in the `mvn site` generation process: 
https://github.com/Steffengreiner/Joint_Compilation_Demo/tree/development

Calling `mvn site` generates the site folder as expected with the groovy and java classes in the "site/apidocs" folder. 
However the documentation of the groovy class is missing.
Interestingly the documentation can be seen in the "gapidocs" folder.  
Is this a bug or am i missing something during the site generation process? 

I included the following snippets in the parent pom Snapshot: 

```<plugin>
<groupId>org.codehaus.gmavenplus</groupId>  
        <artifactId>gmavenplus-plugin</artifactId>
        <version>1.9.0</version>
        <executions>
          <execution>
            <id>default</id>
            <goals>
              <goal>addSources</goal>
              <goal>addTestSources</goal>
              <goal>generateStubs</goal>
              <goal>compile</goal>
              <goal>generateTestStubs</goal>
              <goal>compileTests</goal>
              <goal>removeStubs</goal>
              <goal>removeTestStubs</goal>
            </goals>
          </execution>
          <execution>
            <id>site</id>
            <phase>site</phase>
            <goals>
              <goal>generateStubs</goal>
              <goal>generateTestStubs</goal>
              <goal>groovydoc</goal>
              <goal>groovydocTests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```
The full parent pom can be found here: 
https://github.com/qbicsoftware/parent-poms/tree/development

**Comment by keeganwitt** [comment]
They're in gapidocs on purpose, this is to distinguish javadocs and groovydocs.  You can override this, however, see http://groovy.github.io/GMavenPlus/groovydoc-mojo.html#groovyDocOutputDirectory.

**Comment by Steffengreiner** [comment]
That did the trick! Thank you very much 👍
