### ISSUE TITLE
Support <skip> directive in <configuration> element

### ISSUE THREAD

**Issue by sebthom** [groovy/GMavenPlus#162]
Please add support for the <skip> directive in <configuration> elements (per execution).

I know I can also conditional test for a property directly in Groovy but by having a <skip> option the Groovy does not need to be loaded which results in faster builds if gmaven plugin execution is not required.

**Comment by keeganwitt** [comment]
I'm trying to think of the least disruptive way of accommodating this (given the skips we already have).  Was there a particular use case you are trying to solve?  Like skipping script execution?

**Comment by sebthom** [comment]
What "skips" are you referring too?

We are defining several different executions of the gmaven-plus-plugin in different life cycle phases to perform various activities e.g. programmatically download/unpack/processing other artifacts, injecting maven properties etc.

For certain builds we want to exclude some or all of the executions by specifying custom maven profiles which then sets certain maven properties. We want to reference these properties in the `<execution><configuration><skip>${myprop}</skip></configuration></execution>` to completely skip the execution.

**Comment by keeganwitt** [comment]
The existing skips are:
* All the GroovyDoc goals have a `skipGroovyDoc` property
* All the test goals have a `skipTests` property

When I asked I about executions, I was wondering what goals were being used where this would be useful.

**Comment by sebthom** [comment]
We are only using the "execute" goal but with multiple executions in different phases.

**Comment by keeganwitt** [comment]
OK. Perhaps just adding another property to that mojo would be sufficient (kinda continues the pattern I started, though I wasn't really thinking of it being a pattern when those individual features landed).

**Comment by keeganwitt** [comment]
I pushed a snapshot (1.9.1-20200716.025959-1) to [Sonatype OSS Snapshots]( https://oss.sonatype.org/content/repositories/snapshots/) with a new property added to the execute mojo.  If that seems reasonable to you, I'll go ahead and ship.

**Comment by sebthom** [comment]
@keeganwitt looks good to me. thanks a lot!!

**Comment by spyhunter99** [comment]
i'm using version 2.1.1 and adding `<skipScriptExecution>` in the configuration element does not seem to have an affect. Is there something else i'm missing with this?

**Comment by keeganwitt** [comment]
You need to have
```xml
<configuration>
  <skipScriptExecution>true</skipScriptExecution>
</configuration>
```

Is that what you tried?

I double-checked the [skip logic](https://github.com/groovy/GMavenPlus/blob/22cadd69944fd80345e924547bf0e156a2a31ab3/src/main/java/org/codehaus/gmavenplus/mojo/ExecuteMojo.java#L112-L115). I don't see any reason it shouldn't be working.

**Comment by spyhunter99** [comment]
ha i checked the source too and came to the same conclusion. 

turns out i was pointing at the original groovy maven plugin, not this version. Sorry for the confusion
