### ISSUE TITLE
Java 11 + Groovy 3.0.5 compilation fails with "package annotations should be in file package-info.java"

### ISSUE THREAD

**Issue by Enigo** [groovy/GMavenPlus#166]
Hey hey,
I'm migrating some old project to the newer version of Java.
Initial setup
Java 8
gmavenplus-plugin 1.5
groovy-all.version 2.4.5

New setup
Java 11
gmavenplus-plugin 1.10.0
groovy-all.version 3.0.5

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.10.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>addSources</goal>
                            <goal>addTestSources</goal>
                            <goal>generateStubs</goal>
                            <goal>compile</goal>
                            <goal>generateTestStubs</goal>
                            <goal>compileTests</goal>
                            <goal>removeStubs</goal>
                            <goal>removeTestStubs</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
and 
```
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>3.0.5</version>
            <type>pom</type>
        </dependency>
```

I have a quite a lot of groovy classes to be processed, and there are Java classes generated in `target/generated-sources/groovy-stubs/path/to/class` but `mvn clean compile` fails with 
```
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.816 s
[INFO] Finished at: 2020-08-24T17:36:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project soma-connector-definitions-integration: Compilation failure: Compilation failure: 
[ERROR] /project/target/generated-sources/groovy-stubs/path/to/class/MyAwesomeClass.java:[1,1] package annotations should be in file package-info.java
```

do you have any idea what could be the reason for that? 

EDIT
Groovy classes look like this:

```
@IntroAnnotation(id = 1000000)
package com

import com.IntroAnnotation
import com.SomeContext

{ SomeContext context ->
    
    context.someChecks   

}
```

**Comment by Enigo** [comment]
Downgrading groovy-all to `2.4.12` solved the problem, so it is probably not related to this plugin bit rather to either compiler or groovy itself.

**Comment by keeganwitt** [comment]
When I was researching this, I found an SO [question](https://stackoverflow.com/questions/17177821/package-annotations-should-be-in-file-package-info-java) and a Compiler Plugin [issue](https://issues.apache.org/jira/browse/MCOMPILER-71) that mentioned there was a JDK bug in some versions (I'm not sure which or what the JDK bug number is) that was causing this issue.  Have you tried with other JDK versions?

**Comment by Enigo** [comment]
hey @keeganwitt 
I've tried two JDK versions - the very latest one (11.0.8) and a bit older one (11.0.5).
Both didn't work.

**Comment by keeganwitt** [comment]
The difference seems to be that Groovy 2.4 and 2.5 don't put the annotation in the stub, but 3.0 does.

**Comment by Enigo** [comment]
that very much can be!
were you able to reproduce it? do you think that the change in the plugin might be required?

**Comment by keeganwitt** [comment]
I was yes.  But no, this isn't a GMavenPlus issue, but rather a difference in behavior in Groovy.  I'm asking around now to find out whether this change was intentional.  Are you using the annotation for the purposes of JavaDoc/GroovyDoc ?  Honestly the only time I've ever used package annotations is for JavaDoc/GroovyDoc and I'm not clear if it's valid for any other purpose.

If it is for documentation, why are you putting in a class instead of inside a _package-info.groovy_ or _package-info.java_?

**Comment by Enigo** [comment]
well, it is a bit complicated and also legacy project.
But in short:
1. There are two parts - Java and Groovy
2. Annotations on Groovy scripts are used to be able to distinguish between different types of scripts
3. Java part collects all the scripts and performs certain operations based on the given annotation
4. "Certain operations" are preparations of different SQL scripts (yeah, we store Groovy scripts in DB)
5. There are also tests that validate Groovy scripts

**Comment by keeganwitt** [comment]
I never heard back whether this was an intentional change, but I suspect it's something that slipped through the cracks with the new parser, so I opened a bug: https://issues.apache.org/jira/browse/GROOVY-9717.

I'm not really clear on whether Groovy should even be allowing annotations on packages outside of _package-info.groovy_ in the first place, given Java doesn't.

**Comment by Enigo** [comment]
Neat, I see that the bug has been resolved already! 
I'm going to give it a try once the new Groovy version is out
