### ISSUE TITLE
metaClass additions unavailable

### ISSUE THREAD

**Issue by spmallette** [groovy/GMavenPlus#181]
Apache TinkerPop uses gmavenplus to run groovy scripts to start/stop a server (i.e. Gremlin Server) for testing of non-JVM language components (i.e. javascript, .NET, python). The server uses an extension of the `GroovyScriptEngine` which internally sets up a few modifications to some metaclasses (dynamically adds some methods) and when started accepts a separate groovy initialization script to setup the server's internals as part of normal usage. 

Recently I noticed that metaclass changes seem to be ignored and inaccessible to the server initialization script but only when the server is started with gmavenplus (works fine otherwise when started independently). Here is the gmavenplus configuration for our use with our `gremlin-python` module:

https://github.com/apache/tinkerpop/blob/a0d35c268b5ea74411477e743918107609eba754/gremlin-python/pom.xml#L287-L320

where the defined `test-server-start.groovy` is:

https://github.com/apache/tinkerpop/blob/a0d35c268b5ea74411477e743918107609eba754/gremlin-server/src/test/scripts/test-server-start.groovy

and the server initialization script referenced within it [here](https://github.com/apache/tinkerpop/blob/a0d35c268b5ea74411477e743918107609eba754/gremlin-server/src/test/scripts/test-server-start.groovy#L46) is:

https://github.com/apache/tinkerpop/blob/a0d35c268b5ea74411477e743918107609eba754/gremlin-server/src/test/scripts/generate-all.groovy

After much experimentation I noticed that the mere inclusion of a dummy method on the metaclass in the server initializationscript fixes the problem for gmavenplus runs:

https://github.com/apache/tinkerpop/blob/a0d35c268b5ea74411477e743918107609eba754/gremlin-server/src/test/scripts/generate-all.groovy#L62-L67

and the server starts nicely allowing my tests to pass.  Also, interestingly the metaclass that holds the dummy method must be of the exact type that is in use in the script - in my specific case, `GraphTraversalSource` extends `TraversalSource` and adding to `TraversalSource` seemed to have no effect. For further context, note that the lines that fail execution are the `withStrategies()` methods just below the `hack()`. Our extension of `GroovyScriptEngine` adds a new version of  `withStrategies()` which takes an arbitrary `Object...`...it is this method that cannot be found without the addition of `hack().`

Apologies for the complexity of this failure description. I'm not sure how to better explain this issue with less TinkerPop context, but perhaps there is enough of a hint here in what i've described that might allow someone with better knowledge of groovy/gmavenplus to step in and offer some advice or better articulate the possible bug I'm struggling with here or just ask some question that I can fill in some answers for on the way to a solution that allows me to remove `hack()`. Thanks!

**Comment by keeganwitt** [comment]
Offhand, nothing comes to mind. You said this works with Groovy outside GMavenPlus. You sure it's the same version of Groovy and Java?

**Comment by keeganwitt** [comment]
I'm not totally following how you are executing outside GMavenPlus. You're just calling with `groovy generate-all.groovy`?  The way GMavenPlus is executing scripts is by instantiating a `groovy.lang.GroovyShell`, then invoking `evaluate()` on it.

**Comment by spmallette** [comment]
> You sure it's the same version of Groovy and Java?

yes - it should be

> You're just calling with groovy generate-all.groovy?

We refer to `generate-all.groovy` as an "initialization script" for Gremlin Server. Under normal conditions, an initialization script like `generate-all.groovy` gets executed within the startup of Gremlin Server. Gremlin Server startup includes a process where `ScriptEngine` instances get initialized and relies on a [ScriptEngineManager](https://github.com/apache/tinkerpop/blob/7fe4a8d60d44d9e59fe2727aeab54ad12c9d7c7e/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/DefaultGremlinScriptEngineManager.java) to do that. It is in here that the initialization script gets executed.  So, ultimately, to answer your question, `generate-all.groovy` gets executed inside of a `ScriptEngine` context via `eval()`:

https://github.com/apache/tinkerpop/blob/7fe4a8d60d44d9e59fe2727aeab54ad12c9d7c7e/gremlin-core/src/main/java/org/apache/tinkerpop/gremlin/jsr223/DefaultGremlinScriptEngineManager.java#L460

**Comment by keeganwitt** [comment]
I think I need to find some way to reproduce this in a simpler case to dig into exactly what's happening.  What happens when you print metaClass?  Is it null?

**Comment by spmallette** [comment]
> I think I need to find some way to reproduce this in a simpler case to dig into exactly what's happening. 

yeah - sorry it's complicated. i figured that if nothing came to mind immediately from my description the case would have to be simplified somehow. 

> What happens when you print metaClass? Is it null?

It prints ok when I change my "hack" line to:

```text
println GraphTraversalSource.metaClass
GraphTraversalSource.metaClass.methods.name.unique().each{ println it }
```

output is:

```text
org.codehaus.groovy.runtime.HandleMetaClass@77b4bc13[groovy.lang.MetaClassImpl@77b4bc13[class org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource]]
equals
getClass
hashCode
notify
notifyAll
toString
wait
E
V
addE
addV
clone
close
getAnonymousTraversalClass
getBytecode
getGraph
getStrategies
inject
io
tx
with
withBulk
withComputer
withPath
withRemote
withSack
withSideEffect
withStrategies
withoutStrategies
```

> When I added a method via metaClass to a class in the script block, that worked fine in my test.

Perhaps further clarification is required. We have a class called `Gremlin`Loader` which statically sets up all our metaprogramming stuff - you can see the related classes here:

https://github.com/apache/tinkerpop/tree/master/gremlin-groovy/src/main/groovy/org/apache/tinkerpop/gremlin/groovy/loaders

So, with that we can call `GremlinLoader.load()` and all the sugar syntax for Gremlin in Groovy gets initialized. We automatically call that `load()` method when our `ScriptEngine` is created (thus, just before this initialization script is executed within it). Somehow, by adding my "hack()" metamethod the changes made by `load()` just start working as expected. Interestingly, if I place `GremlinLoader.load()` in that initialization script instead of the "hack()" it has no effect. Explicitly adding "something" to the metaclass in the script itself is the key to letting `GremlinLoader.load()` work and I think it is isolated to gmavenplus (i.e. GroovyShell??) since I don't need that "hack()" line in any other context where Gremlin Server is initialized.

if you can think of other things i might try to help simplify the problem, I'd be happy to try. perhaps there is a way to take gmavenplus/maven out of the mix so that we could potentially isolate to the GroovyShell? would that be helpful somehow?

**Comment by keeganwitt** [comment]
> if you can think of other things i might try to help simplify the problem, I'd be happy to try. perhaps there is a way to take gmavenplus/maven out of the mix so that we could potentially isolate to the GroovyShell? would that be helpful somehow?

If it's not super onerous, that might be helpful. At the moment, I'm not sure if I missed doing some config of GroovyShell in GMavenPlus or if it's a bug/limitation of Groovy itself.  I suspect the latter, since I haven't seen anything in other usages that I don't have, but I don't have any proof at the moment.

**Comment by keeganwitt** [comment]
One possibility I thought of, but haven't totally thought through is whether there were different classloaders used when adding the magic in vs when script is invoked, but that doesn't really explain why your hack would fix it...

**Comment by keeganwitt** [comment]
I just did a release (1.12.0) to fix a classloader issue relating to multimodule projects. I'm not sure if that will help with this issue (since I still don't completely understand what's going on), but it might be worth giving that a shot.

**Comment by spmallette** [comment]
I got pulled away from trying to simplify this case a bit further (hopefully i can get back to it soon). I did upgrade to 1.12.0 and had to adjust my pom dependencies a bit as it failed on just a version bump. I'm not completely sure I understand why:  

https://github.com/apache/tinkerpop/commit/b56ec8306f0b3a100a910e8e696c9e8746879df5

Sadly, though your change didn't resolve the problem and my hack remains...

**Comment by keeganwitt** [comment]
Where's the log from the build from that change?

**Comment by spmallette** [comment]
I re-ran the python job to (travis invariably throws connection errors stuffs) - it's green now. 

The script error you noticed is a failing as expected as it is testing an error condition. Note that the actual log for the build that runs that server initialization script is here:

https://travis-ci.org/github/apache/tinkerpop/jobs/749686753

not sure why travis can't find the gmaven plugin for python but found it fine for in other contexts where it is used in our build. i've re-run that build several times now and get the same error. perhaps it's a travis cache issue somehow. will check back on it tomorrow. works fine for me locally (again, with my hack in place)

**Comment by keeganwitt** [comment]
It's not saying it can't find GMavenPlus, it's saying it can't find one of your project modules (`Could not find artifact org.apache.tinkerpop:gremlin-python:jar:3.4.10-SNAPSHOT`).

**Comment by spmallette** [comment]
You're right:

``text
119.53s$ touch gremlin-python/.glv && mvn clean install -q -DskipTests -Dci && mvn verify -pl gremlin-python
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.12.0:execute (generate-dsl) on project gremlin-python: Execution generate-dsl of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.12.0:execute failed: Plugin org.codehaus.gmavenplus:gmavenplus-plugin:1.12.0 or one of its dependencies could not be resolved: Could not find artifact org.apache.tinkerpop:gremlin-python:jar:3.4.10-SNAPSHOT
```

hmm - wonder why that is? that command above the error clearly builds the whole project (i.e. with gremlin-python) then runs the tests. works fine locally for me....

**Comment by keeganwitt** [comment]
If 1.12 broke this, I wonder if that extension is coming from a submodule that ran previous to the one GMavenPlus is executing in.  That was the bug I was trying to fix, was that the classloader kept getting more and more submodules added to it, as each module executed.  If that is the case, then you should have a dependency on that previous module rather than the current one.
I'm guessing a bit here, I still don't understand your setup.  I'll try to read your source more once I get some time.

**Comment by spmallette** [comment]
The basic premise with our build is that we use maven to orchestrate the build operations of both Java and non-JVM components. TinkerPop supports Java, Groovy, Python, .NET and Javascript and for the latter three we hook into the maven lifecycle so that `mvn clean install` (for example) will build and test the entire project and all those languages to ensure everything is working as it should.  GMavenPlus is helpful for the non-JVM builds because it allows us to run a Groovy script that will start/stop our Gremlin Server so that we can test against it. So for the gremlin-python module, there is Java code in there that becomes relevant to Gremlin Server when it starts and then later in the maven lifecycle, native python commands trigger pytest executions against that server.  Does that help frame what we are doing a little bit better?

**Comment by keeganwitt** [comment]
Glad you figured the python module problem out. That was kinda my suspicion.

So the setup here is
1. _test-server-start.groovy_ launches `GremlinServer`
    1. `GremlinServer` calls `GremlinLoader.load()`
        1. `GremlinLoader` invokes classes like `StepLoader` which applies metaClass customizations
    1. `GremlinServer` then uses JSR223 to create a `GremlinScriptEngine`
    1. `GremlinServer` executes _generate-all.groovy_ (in a separate thread, if I'm not mistaken).

Right?

It appears to me Gremlin's script engine uses `Thread.currentThread().getContextClassLoader()` as the script's parent classloader. Given that, I'm not sure the metaclass registry will have the additions to that copy of the metaclass.

When I test with
_script.groovy_
```groovy
new com.github.keeganwitt.FooCustomizer().customize()
assert new com.github.keeganwitt.Foo().sayHi() == "Hi!"
```
_FooCustomizer.groovy_
```groovy
package com.github.keeganwitt
class FooCustomizer {
    void customize() {
        Foo.metaClass.sayHi = { ->
            return "Hi!"
        }
    }
}
```
_Foo.groovy_
```groovy
package com.github.keeganwitt
class Foo { }
```
It passes.

**Comment by spmallette** [comment]
Your description of what is happening there is correct. 

> But if I'm right, I don't understand why the hack would fix this.

the hack is the so completely puzzling to me. i can't imagine what it would trigger to allow this to work and the case is so convoluted (though you understand it now and thanks for taking the time to do so) it's not simple to recreate in my mind.  I still need to try to run this script through the GroovyShell to get maven/gmavenplus out of the picture. perhaps i can get to that today or tomorrow.

**Comment by keeganwitt** [comment]
I haven't been able to reproduce this in a little test project yet, even when FooCustomizer instantiates a new classloader to run the metaclass method adding on.

I did have one other idea. Since the Gremlin script engine manager is using `Thread.currentThread().getContextClassLoader()`), you could do this within the script executed by GMavenPlus; `Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader())`.

**Comment by spmallette** [comment]
Finally buckled down and did some more testing. When I run the `test-server-start.groovy` in groovysh I don't need the weird metclass hack in `generate-all.groovy`  🤷 The server starts properly and I can make use of the added methods that the `GremlinGroovyScriptEngine` tacks in. 

Does that somehow isolate the issue to gmavenplus then? 

I did try adding that line you suggested of `Thread.currentThread().setContextClassLoader(this.getClass().getClassLoader())` to `test-server-start.groovy` but it didn't change the outcome...the server did not start properly.

**Comment by keeganwitt** [comment]
Yes and no. I think the problem is the Classloader used vs the expectations in the script. This is partially under my control, partially not (since Maven creates 2 levels of classloaders, plus the system level before my plugin gets loaded, but then I have control after that).

I'm still trying to create a script that recreates this problem.

**Comment by spmallette** [comment]
I've never debugged a maven plugin before - is it possible to somehow debug it from the TinkerPop build where the failure is happening? of course, it's not a simple demonstration of the problem...

**Comment by keeganwitt** [comment]
I haven't done that really myself. You can use `mvndebug` instead of `mvn`, and attach a debugger, like any Java process. Though I'm not sure how easy it'd be to see, since I use reflection to access Groovy classes.

`mvn --projects gremlin-python verify` is still passing for me on 3.4-dev branch, even with the hack commented out though.

**Comment by spmallette** [comment]
It probably just passes because your build isn't setup to run python. We skip the native python aspects of the build for the sake of the JVM developers. You can enable by adding an empty `.glv` file to the root of `gremlin-python`: `touch gremlin-python/.glv` or just build with the `-Pglv-python` profile. More specifics here assuming the build of the `master` branch:

https://tinkerpop.apache.org/docs/3.5.0-SNAPSHOT/dev/developer/#python-environment

That said, I've just learned something interesting. This is only a problem on our `3.4-dev` release branch that supports Groovy 2.5.x. On the `master` branch with Groovy 3.x the hack is not needed. 

I suppose my position on this issue shifts a bit now. If it resolves itself with Groovy 3.0 and you aren't enlightened as to what the problem might be given this new development, I'm inclined to let the hack stick around on our `3.4-dev` branch as this is clearly not an easy problem to sort out and perhaps even more complicated now by the fact that the issue could be something in Groovy itself and no longer isolated to gmavenplus. As long as the hack for testing `3.4-dev` works for the next 6 months to a year, which I believe is the rough life span remaining for that branch, I think that it's not worth hassling about this for our sake and we can just close this issue. what do you think?

**Comment by keeganwitt** [comment]
> It probably just passes because your build isn't setup to run python. We skip the native python aspects of the build for the sake of the JVM developers.

Ah, I figured I must have missed something.

I'm OK with closing, but I'm also willing to help keep looking if you'd like.  I think it's likely a combination of classloader assumptions of different things not playing nice together, although I still don't have a very clear picture of what, specifically.

**Comment by spmallette** [comment]
Thanks for offering continued support. It's appreciated. I think we can close it for now. If something changes and it becomes a blocker on our end for some reason I suppose I'll just raise the issue up again. Feel free to put your brain cells to work elsewhere 😄
