### ISSUE TITLE
Update the wiki documentation with latest Spock stable release version instead of milestone version

### ISSUE THREAD

**Issue by s4ik4t** [groovy/GMavenPlus#194]
In the [Examples](https://github.com/groovy/GMavenPlus/wiki/Examples) Wiki page as of now Spock milestone version is used i.e. `2.0-M5-groovy-3.0`. We should update this to latest stable release version of `2.0-groovy-3.0`.

**Comment by keeganwitt** [comment]
Updated. Thank you!

**Comment by s4ik4t** [comment]
Many thanks ☺️
