### ISSUE TITLE
generateTestStubs  failed: Unrecognized target bytecode: '8'

### ISSUE THREAD

**Issue by QBH-insist** [groovy/GMavenPlus#205]
hi, i have a compile problem when i try to use spock and gmavenplus.

**command:** `mvn test`
**result:** 
![image](https://user-images.githubusercontent.com/39401478/145962693-b7b37035-ed43-46ab-9f46-5364936895fe.png)

**java version:**  `"1.8.0_151"`

**parent pom.xml**:
```
        <groovy.version>2.5.14</groovy.version>
        <spock.version>1.3-groovy-2.5</spock.version>
        <powermock.version>2.0.4</powermock.version>
         <!-- spock -->
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-core</artifactId>
            <version>${spock.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.spockframework</groupId>
            <artifactId>spock-spring</artifactId>
            <version>${spock.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <type>pom</type>
            <version>${groovy.version}</version>
            <exclusions>
                <exclusion>
                    <artifactId>groovy-test-junit5</artifactId>
                    <groupId>org.codehaus.groovy</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>groovy-testng</artifactId>
                    <groupId>org.codehaus.groovy</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>org.junit.vintage</groupId>
                    <artifactId>junit-vintage-engine</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
         <build>
            <finalName>demo</finalName>
            <plugins>
                <plugin>
                    <groupId>org.codehaus.gmavenplus</groupId>
                    <artifactId>gmavenplus-plugin</artifactId>
                    <version>1.13.1</version>
                    <executions>
                        <execution>
                          <goals>
                              <goal>addSources</goal>
                              <goal>addTestSources</goal>
                              <goal>generateStubs</goal>
                              <goal>compile</goal>
                              <goal>generateTestStubs</goal>
                              <goal>compileTests</goal>
                              <goal>removeStubs</goal>
                              <goal>removeTestStubs</goal>
                          </goals>
                      </execution>
                  </executions>
              </plugin>
              <plugin>
                  <groupId>org.apache.maven.plugins</groupId>
                  <artifactId>maven-surefire-plugin</artifactId>
                  <version>3.0.0-M5</version>
                  <configuration>
                      <includes>
                          <include>**/*Spec.class</include>
                          <include>**/*Test.java</include>
                      </includes>
                  </configuration>
              </plugin>
          </plugins>
        </build>
```

**Comment by keeganwitt** [comment]
My guess is that you have `maven.compiler.target` set to `8`. It should be `1.8`. If for some reason that doesn't work for you, you can do
```xml
<configuration>
    <targetBytecode>1.8</targetBytecode>
<configuration>
```
in the GmavenPlus plugin element.

**Comment by QBH-insist** [comment]
> My guess is that you have `maven.compiler.target` set to `8`. It should be `1.8`. If for some reason that doesn't work for you, you can do
> 
> ```
> <configuration>
>     <targetBytecode>1.8</targetBytecode>
> <configuration>
> ```
> 
> in the GmavenPlus plugin element.

You are right，thanks.
Now i meet another problem, The file can compile but not run. Look forward to your reply.
![image](https://user-images.githubusercontent.com/39401478/146147896-5e69cc2a-2d9b-4de5-8623-4a4c1d7f1ca2.png)
![image](https://user-images.githubusercontent.com/39401478/146147932-9a3cbd6f-fc81-429e-9035-8b9d56bc3491.png)

**Comment by keeganwitt** [comment]
Are your Spock tests files named like `*Spec.groovy`?  Because your Surefire configuration currently expects that.

**Comment by QBH-insist** [comment]
> > My guess is that you have `maven.compiler.target` set to `8`. It should be `1.8`. If for some reason that doesn't work for you, you can do
> > ```
> > <configuration>
> >     <targetBytecode>1.8</targetBytecode>
> > <configuration>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in the GmavenPlus plugin element.
> 
> You are right，thanks. Now i meet another problem, The file can compile but not run. Look forward to your reply. ![image](https://user-images.githubusercontent.com/39401478/146147896-5e69cc2a-2d9b-4de5-8623-4a4c1d7f1ca2.png) ![image](https://user-images.githubusercontent.com/39401478/146147932-9a3cbd6f-fc81-429e-9035-8b9d56bc3491.png)

I found the reason why test not run. 
I excluded 'junit-vintage-engine' dependency， this is wrong.  Thanks
`<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
           
        </dependency>`

**Comment by keeganwitt** [comment]
I'm glad you were able to get it working.  I'll close this issue now, but if you have further problems, let me know and I'll re-open.
