### ISSUE TITLE
The generateStubs goal ignores @BaseScript for Groovy scripts

### ISSUE THREAD

**Issue by crizzis** [groovy/GMavenPlus#209]
Base script class: 

```
import java.util.function.Predicate

import static groovy.lang.Closure.DELEGATE_ONLY

abstract class TransformDsl extends Script {
    ...
}
```

`@BaseScript` - annotated Groovy script: 

```
import groovy.transform.BaseScript

@BaseScript TransformDsl transformDsl

... // script body
```

Generated stub: 

```
public class literals
  extends groovy.lang.Script {
;
public literals
() {}
public literals
(groovy.lang.Binding context) {
super ();
}
public static  void main(java.lang.String... args) { }
public  java.lang.Object run() { return (java.lang.Object)null;}
}
```

Tried both the annotated variable and annotated package syntax, same result

**Comment by keeganwitt** [comment]
I believe this is an issue in Groovy's stub generator. I don't think the stub generator looks handles the `@BaseScript` annotation.
If you don't mind my asking, why do you need it in the stubs? This feature is typically used in Groovy scripts, which wouldn't be compiled (or shared with Java). But if this is something you need, we can [open a Jira](https://issues.apache.org/jira/projects/GROOVY).

**Comment by crizzis** [comment]
Opened a JIRA here: https://issues.apache.org/jira/browse/GROOVY-10584?filter=-2

Closing this ticket. Thanks for your help!

**Comment by keeganwitt** [comment]
Thanks for reporting this!
