### ISSUE TITLE
<classifier>indy</classifier> as per wiki does not work

### ISSUE THREAD

**Issue by wilx** [groovy/GMavenPlus#212]
The https://github.com/groovy/GMavenPlus/wiki/Examples#invokedynamic-compilation section suggests to use the following dependency to get the invokedynamic variant:¨

```xml
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <!-- any indy version of Groovy \>= 2.0.0-beta-3 should work here -->
      <version>3.0.9</version>
      <type>pom</type>
      <classifier>indy</classifier>
    </dependency>
```

However, there is no such artifact.

**Comment by keeganwitt** [comment]
Oops, you're right. Copy/paste error. I've corrected the example. Thank you for mentioning it!
