### ISSUE TITLE
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.8.1:compileTests 

### ISSUE THREAD

**Issue by ankitaprabhu** [groovy/GMavenPlus#213]
Hello, 
 
We are facing issue as "**[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.8.1:compileTests (default) on project c4p-project-plan: Error occurred while calling a method on a Groovy class from classpath.: InvocationTargetException: org/codehaus/groovy/transform/stc/AbstractExtensionMethodCache: org.codehaus.groovy.transform.stc.AbstractExtensionMethodCache -> [Help 1]**" attached reference for more details while executing "**mvn clean install**" cmd on our project.

<img width="956" alt="Error" src="https://user-images.githubusercontent.com/18416196/162928245-a8438e2c-6383-4697-9c52-97d3a4c7e446.PNG">

Our POM looks like below.
1. Parent POM : https://github.wdf.sap.corp/SAPPIN/c4p-project-plan/blob/test/master-version-upgrade/pom.xml

![image](https://user-images.githubusercontent.com/18416196/162928803-c6bd4adb-e976-43f5-bc60-5df002bc29a4.png)

2. Srv POM : https://github.wdf.sap.corp/SAPPIN/c4p-project-plan/blob/test/master-version-upgrade/srv/pom.xml

![image](https://user-images.githubusercontent.com/18416196/162928558-094d4020-4198-4b8c-9e79-8e335bb11aac.png)

We upgraded the spring oot versio to 2.6.6 after that we are facing the above issue as attached.

Kindly help us here to resolve the same or do let me know in case of any further info if needed.

Best Regards,
Ankita Prabhu.

**Comment by keeganwitt** [comment]
Can I see the stacktrace (with `-e`)?

**Comment by ankitaprabhu** [comment]
Hi @keeganwitt ,

PFA of stacktrace as suggetsed on executing mvn clean install command.
[StackTrace.txt](https://github.com/groovy/GMavenPlus/files/8478163/StackTrace.txt)

Best Regards,
Ankita Prabhu.

**Comment by keeganwitt** [comment]
It appears to me you are using the `AbstractExtensionMethodCache` transformation somewhere. This was added in Groovy 3.0, but you are trying to use Groovy 2.5.8, which won't have this available.

**Comment by keeganwitt** [comment]
Closing stale issue. If you believe this should be reopened, please leave a comment.
