### ISSUE TITLE
Add JDK 19 support

### ISSUE THREAD

**Issue by Joan-Lara-Miquel** [groovy/GMavenPlus#230]
Hi, 

once updating my spring boot project to Java 19, via some properties:
```
<properties> 
     <java.version>19</java.version>
</properties>
```

I get the following error when running the `compile` and `compileTests` goals:

 `[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:2.0.0:compileTests (default) on project foo: Execution default of goal org.codehaus.gmavenplus:gmavenplus-plugin:2.0.0:compileTests failed: Unrecognized target bytecode: '19'. This check can be skipped with 'skipBytecodeCheck', but this may result in a different target bytecode being used.`

This is my plugin setup:

```
<plugin>
        <groupId>org.codehaus.gmavenplus</groupId>
        <artifactId>gmavenplus-plugin</artifactId>
        <version>2.0.0</version>
        <executions>
          <execution>
            <goals>
              <goal>compile</goal>
              <goal>compileTests</goal>
            </goals>
          </execution>
        </executions>
</plugin>
```
Can 19 be added to the bytecode verifications?

**Comment by keeganwitt** [comment]
This will be in the next release, which I'll aim to do this week. In the meantime, you can temporarily skip the bytecode verification to suppress this failure.
