### ISSUE TITLE
Incorrect groupId of the groovy dependency in wiki

### ISSUE THREAD

**Issue by mguelton** [groovy/GMavenPlus#236]
Wiki pages incorrectly state that the groupId of the groovy dependency in version 4.0.6 is `org.codehaus.groovy`:
```xml
<dependency>
    <groupId>org.codehaus.groovy</groupId>
    <artifactId>groovy</artifactId>
    <!-- any version of Groovy \>= 1.5.0 should work here -->
    <version>4.0.6</version>
    <scope>runtime</scope>
</dependency>
```
According to https://groovy.apache.org/download.html#buildtools, the `groupId` should be `org.apache.groovy` for groovy version 4.0 and greater.

**Comment by keeganwitt** [comment]
Thanks for pointing this out! I missed this when I updated the pages. Fixed now.
