### ISSUE TITLE
Documentation: Indy doc doesn't work

### ISSUE THREAD

**Issue by kenwdelong** [groovy/GMavenPlus#258]
The [page](https://github.com/groovy/GMavenPlus/wiki/Examples#invokedynamic-compilation) for invoke dynamic support shows this 

```
    <dependency>
      <groupId>org.apache.groovy</groupId>
      <artifactId>groovy</artifactId>
      <!-- any indy version of Groovy \>= 2.0.0-beta-3 should work here -->
      <version>4.0.6</version>
      <classifier>indy</classifier>
    </dependency>
```

But there is no such artifact.  There are apparently no `indy` jars in 4.x.

Related to https://github.com/groovy/GMavenPlus/issues/212

**Comment by keeganwitt** [comment]
Ah, darn it. I missed that when I was doing a bulk replace of the Groovy versions. Updated. Lemme know if you think it needs more editing. Thanks for reporting!

**Comment by kenwdelong** [comment]
Does that mean we don't need 
```<invokeDynamic>true</invokeDynamic>```
in Groovy 4.0 and GMavenPlus 3.0.0?

**Comment by keeganwitt** [comment]
That's right. It won't hurt anything if you do, but if GMavenPlus sees you are using Groovy 4+ it will turn that on already for you (https://github.com/groovy/GMavenPlus/blob/b3ffc4028fcf7f27229186cf0fc2279aabffaf6d/src/main/java/org/codehaus/gmavenplus/mojo/AbstractCompileMojo.java#L445) and if you set it false with 4+ it will ignore that and still turn it on.
