### ISSUE TITLE
Update CI to use multiple Java and Groovy versions

### ISSUE THREAD

**Issue by bmarwell** [groovy/GMavenPlus#267]
The CI could be updated to a newer setup-java action which includes:

* Java 11
* Java 21 (no 17 -- if it works on 21, it is fine, too!)
* Groovy 4.0.0 (earliest version, Java 11 only)
* Groovy 4.0.11 (first to support Java 21)
* Latest Groovy

Maybe enhance some parameters (memory, no-transfer-progress), etc.

WDYT?

**Comment by keeganwitt** [comment]
I haven't really seen many problems with Java versions to make that worth adding time to the builds for (or complexity of cros-product) IMO. So, I'd probably say just test with whatever is the latest LTS.

I think we should have a test for the latest of each major version of Groovy still supported by the team. At the time of writing, that would be
* 2.5.23
* 3.0.19
* 4.0.15
* 5.0.0-alpha-2

**Comment by keeganwitt** [comment]
> Can try with two versions (latest 3.x and latest 4.x). However, the latest 3.x groovy doesn't support Java 21 nor Java 17. Would need to use 11 for that.

Ah, good point. Maybe we just do 11 across the board.

**Comment by bmarwell** [comment]
Fixed on https://github.com/groovy/GMavenPlus/commit/981d4e7c62c135e60ba5e72ad18c65c5acd22a5d
