### ISSUE TITLE
3.0.1 release jar is corrupted

### ISSUE THREAD

**Issue by eugene-sadovsky** [groovy/GMavenPlus#280]
Hello, I'm having a problem with 3.0.1 jar in  [maven central](https://repo1.maven.org/maven2/org/codehaus/gmavenplus/gmavenplus-plugin/3.0.1/) . My builds started to fail and the jar itself can not be unpacked
```
java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
```

**Comment by pnarozny** [comment]
@keeganwitt FYI

**Comment by keeganwitt** [comment]
Thanks for reporting this! I'm on it.

**Comment by keeganwitt** [comment]
I'm not exactly sure what happened. I had some trouble during by build process getting the artifacts signed and deployed. This time it ran cleanly, so it should work now.

**Comment by pnarozny** [comment]
works fine again. Thank you for the swift fix. 🚀
