### ISSUE TITLE
maven site is a mix of version 3.0.2 and 2.1.0

### ISSUE THREAD

**Issue by sellersj** [groovy/GMavenPlus#295]
3.0.2 site
https://groovy.github.io/GMavenPlus/index.html
2.1.0 site
https://groovy.github.io/GMavenPlus/execute-mojo.html

Reminds me of a similar issue where this was the fix:
https://github.com/jeremylong/DependencyCheck/pull/6244/files

**Comment by keeganwitt** [comment]
Hmm. I'm not sure how this happened. Thank you for reporting this!

**Comment by keeganwitt** [comment]
I've re-published the 3.0.2 site. Let me know if you notice anything else amiss.
