### ISSUE TITLE
Compilation failure 

### ISSUE THREAD

**Issue by peome** [groovy/GMavenPlus#40]
Hi, I am trying to perform an automated release under Teamcity of a java 8/groovy project with maven 2.2.1. I have one module called B who is a java only jar module and a module A who is a groovy only module that depends on B module. 
When I run mvn -U release:prepare --batch-mode -e locally all is ok and the release get prepared but when I try to run in my teamcity environment I get the following error:

  [INFO] [INFO] Using Groovy 2.3.9 to perform compile.
  [INFO] [INFO] Error occurred while calling a method on a Groovy class from classpath.
  [INFO] com/a/b/c/XXX : Unsupported major.minor version 52.0

Gmavenplus plugin config is:

       <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>addSources</goal>
                            <goal>addTestSources</goal>
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <targetBytecode>1.8</targetBytecode>
                    <verbose>true</verbose>
                </configuration>
            </plugin>

      <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.3.9</version>
            <exclusions>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>jsp-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>jcl-over-slf4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

Maven compiler config:

    <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.2</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
                <fork>true</fork>
                <compilerVersion>1.8</compilerVersion>
                <executable>${JAVA_1_8_HOME}/bin/javac</executable>
                <compilerArguments>
                </compilerArguments>
                <encoding>UTF-8</encoding>
                <optimize>true</optimize>
            </configuration>
        </plugin>

And logs from Teamcity show me that there is and java 6 version in PATH environment variable but maven is being called with java 8. 

Why is gmavenplus plugin using java 6 compiler? 
Is there anyway to force gmavenplus plugin to run with a certain JVM?

**Comment by keeganwitt** [comment]
It don't use Java 6.  It defaults to Java 5 (just like the maven compiler plugin currently does).  But since you have explicitly declared a bytecode version to use, it will use that.  What is the value of the `java.version` property?  I would think you'd want that to be 1.8 as well.

I think the problem is you're compiling against Java 8, but you're invoking with a Java that is older than 8 (maybe 6?) at runtime.  I'd double check your TeamCity path.

**Comment by peome** [comment]
The java.version property value is 1.8. The error happens at compilation time, during gplus compilation.
Before the error I have the following warning:

[gplus:compile {execution: default}]
[INFO] Mar 23, 2015 7:39:05 AM org.codehaus.groovy.runtime.m12n.MetaInfExtensionModule newModule
[INFO] WARNING: Module [groovy-all] - Unable to load extension class [org.codehaus.groovy.runtime.NioGroovyMethods]

I hope this could help.

**Comment by keeganwitt** [comment]
I did kinda mis-word that.  What I suspect might be happening here is that locally you are using 8, but TeamCity is trying to use Java 6 or 7 to compile to 8.

The only time I've seen this error is when I wasn't using the Java I thought I was.  Could you try adding `-V` to the arguments so that the Java version is displayed during the build so we can rule that out?

**Comment by keeganwitt** [comment]
I close issues if I don't hear back within a month.  If you are still experiencing this issue, I'm happy to reopen.
