### ISSUE TITLE
execute goal failed on windows

### ISSUE THREAD

**Issue by sshikov** [groovy/GMavenPlus#42]
I have a script 
```xml
<script><![CDATA[
   def ant = new AntBuilder()
   ant.echo('Copying distrib!')
   ant.scp(
      file: '...'
      , todir: '...'
      , verbose: true
      , trust: true
      , keyfile: '${user.home}/.ssh/rsa_2048.ppk'
   )
   ant.echo('distrib complete')
]]></script>
```

and its failed on Windows with error message: 

Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.5:execute (default) on project bundles: Error occurred while calling a method on a Groovy class from classpath. InvocationTargetException: startup failed:
[ERROR] Script1.groovy: 9: unexpected char: '\' @ line 9, column 47.
[ERROR] , keyfile: 'C:\Users\ssh
[ERROR] ^

Because ${user.home} contains '\' characters. I'm not sure this is GMavenPlus issue.

**Comment by sshikov** [comment]
The same issue with GMaven.

**Comment by abelsromero** [comment]
Hi,

I'm not an expert on the matter but it may be a problem with the script itself.
If `keyfile` requires a path, you can try to convert it to File to normalize it with the cannonical form:
```
("${user.home}/.ssh/rsa_2048.ppk" as File).cannonicalPath
```

**Comment by keeganwitt** [comment]
The problem is that Maven filters ${user.home} to `C:\Users\...` before it even gets to GMavenPlus.  So it sees the text as though you literally put in `C:\Users\...`, which of course is a bad String.

As I mention on the last line of the first script block in my execute scripts [example](https://github.com/groovy/GMavenPlus/wiki/Examples#execute-scripts), you can use `$foo` instead of `${foo}` to refer to variables so that it doesn't match Maven's pattern.  But in your case you are relying on Maven's filtering, so even if you could prevent Maven from substituting, it would be useless to Groovy.  I suggest avoiding Maven's filtering altogether and just do something like

```xml
<script><![CDATA[
   def ant = new AntBuilder()
   ant.echo('Copying distrib!')
   ant.scp(
      file: '...'
      , todir: '...'
      , verbose: true
      , trust: true
      , keyfile: System.properties['user.home'] + '/.ssh/rsa_2048.ppk'
   )
   ant.echo('distrib complete')
]]></script>
```

**Comment by sshikov** [comment]
Keegan, I think you're right. By the way, is it possible to execute script from file, and avoid filtering this way? I can't find such example yet.

**Comment by keeganwitt** [comment]
Absolutely.  Here's the example from the [execute scripts](https://github.com/groovy/GMavenPlus/wiki/Examples#execute-scripts) section
```xml
<script>file:///${project.basedir}/src/main/resources/groovyScripts/someScript.groovy</script>
```
In the version I haven't released yet, I've also [added](https://github.com/groovy/GMavenPlus/issues/36) the ability to also configure without the URI prefix, like this
```xml
<script>${project.basedir}/src/main/resources/groovyScripts/someScript.groovy</script>
```
I'll probably release that in the next week or so.

**Comment by sshikov** [comment]
BTW, I've found good explanation here: http://maven.apache.org/shared/maven-filtering/

**Comment by keeganwitt** [comment]
I'm not completely sure why, but neither `\${user.home}` or `$${user.home}` seemed to prevent the filtering, despite various places saying that it should.  I even tried
```xml
<properties>
  <dollar>$</dollar>
</properties>
...
${dollar}{user.home}
```
and Maven still filtered it.
