### ISSUE TITLE
Bounded generic in constructor causes compile error

### ISSUE THREAD

**Issue by lispjedi** [groovy/GMavenPlus#47]
Having the following Groovy classes:

```groovy
package test
class A {}
```

```groovy
package test
abstract class BaseGeneric<T extends A> {
    T obj
    protected BaseGeneric(T obj) { this.obj = obj }
}
```

```groovy
package test
class SubGeneric<B extends A> extends BaseGeneric<B> {
    SubGeneric(B obj) { super(obj) }
}
```

The compiler produces an error message on Java code generated by GMavenPlus:
test.SubGeneric.java:[16,8] incompatible types: test.A cannot be converted to B

Looking at the generated Java source code for class SubGeneric, we see:

```java
package test;

import java.lang.*;
import java.io.*;
import java.net.*;
import java.util.*;
import groovy.lang.*;
import groovy.util.*;

public class SubGeneric
<B extends test.A>  extends test.BaseGeneric<B>  implements
    groovy.lang.GroovyObject {
;
public SubGeneric
(B obj) {
super ((test.A)null);
}
public  groovy.lang.MetaClass getMetaClass() { return (groovy.lang.MetaClass)null;}
public  void setMetaClass(groovy.lang.MetaClass mc) { }
public  java.lang.Object invokeMethod(java.lang.String method, java.lang.Object arguments) { return null;}
public  java.lang.Object getProperty(java.lang.String property) { return null;}
public  void setProperty(java.lang.String property, java.lang.Object value) { }
}
```

This cast in the constructor:
super ((test.A)null);

causes a compile error. I really don't understand why, because the generic has to be at least a test.A, so it should theoretically be possible to upcast. But the Java compiler does not like it. It would be OK for him if this was generated instead:

super ((B)null);

**Comment by keeganwitt** [comment]
I think there was a bug discovered in Groovy about this (which it'd have to be anyway -- GMavenPlus doesn't make the stubs, it just calls Groovy to do the work).  What version of Groovy are you using?

**Comment by mstWeal** [comment]
Groovy 2.4.5

**Comment by mstWeal** [comment]
There seem to be a lot of bugs in Groovy regarding generics:
https://issues.apache.org/jira/browse/GROOVY-7204?jql=project%20%3D%20GROOVY%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22generic%22%20ORDER%20BY%20due%20ASC%2C%20priority%20DESC%2C%20created%20ASC

So please feel free to close this bug. I guess I will refrain from using generics in Groovy anymore.

**Comment by keeganwitt** [comment]
I'd ask about this on the [mailing list](http://groovy-lang.org/mailing-lists.html).  I don't know if this bug has already been reported or not, but Jochen or Cedric would know.
