### ISSUE TITLE
Not finding Groovy source in src/main/java

### ISSUE THREAD

**Issue by kenwdelong** [groovy/GMavenPlus#49]
I tried GMavenPlus 1.5 as a migration away from the now dead Groovy Eclipse Compiler.  I keep all my sources, both Java and Groovy, in /src/main/java (I often switch a file from Java to Groovy or back again depending on what it does).

My GMavenPlus compilation fails.  The Java classes that depend on Groovy classes cannot find the class files (or stubs or whatever).

Way up near the top I see:
[INFO] --- gmavenplus-plugin:1.5:generateStubs (default) @ hatch-api ---
[INFO] No sources specified for stub generation.  Skipping.

My guess is that stub generation is looking in /src/main/groovy for Groovy classes.

I'm also guessing there's an easy way to configure this, but I don't know enough about Maven mojos.  I looked through the code, but I couldn't figure out how to specify the source path.

I tried 
```
				<plugin>
					<groupId>org.codehaus.gmavenplus</groupId>
					<artifactId>gmavenplus-plugin</artifactId>
					<version>1.5</version>
					<configuration>
						<sources>
							<source>src/main/java</source>
						</sources>
					</configuration>
                                       etc..
```
but I got

[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.5:addSources (default) on project hatch-api:
Unable to parse configuration of mojo org.codehaus.gmavenplus:gmavenplus-plugin:1.5:addSources for parameter source: Can
not find default setter in class org.apache.maven.shared.model.fileset.FileSet -> [Help 1]

Is there a way to do this?

PS, thanks for working on this project.  Now that GEC is dead, I have to either use GMavenPlus, or migrate all my projects to Gradle, which is a bit of work...

**Comment by keeganwitt** [comment]
Hi Ken.  That's correct, GMavenPlus assumes the Groovy sources will be in `src/main/groovy` and `src/test/groovy`, just as the Groovy plugin for Gradle does.  You've got the right idea, but Maven fileset arguments require both a `directory` and `includes` sections (see the example [here](https://github.com/groovy/GMavenPlus/wiki/Examples#additional-sources)).

If all your groovy sources are in your java directories, this is the configuration you'd use
```xml
<configuration>
  <sources>
    <source>
      <directory>${project.basedir}/src/main/java</directory>
      <includes>
        <include>**/*.java</include>
      </includes>
    </source>
  </sources>
  <testSources>
    <testSource>
      <directory>${project.basedir}/src/test/java</directory>
      <includes>
        <include>**/*.java</include>
      </includes>
    </testSource>
  </testSources>
<configuration>
```

**Comment by kenwdelong** [comment]
Thank you sir!

**Comment by keeganwitt** [comment]
My pleasure.  If you have any other problems, feel free to ping me through our [mailing list](https://groups.google.com/d/forum/gmavenplus).

**Comment by Soontao** [comment]
Thank you :)
