### ISSUE TITLE
Problem finding groovy

### ISSUE THREAD

**Issue by tombensve** [groovy/GMavenPlus#57]
The following isn't GMavenPlus, but only GMaven:

            <plugin>
                <groupId>org.codehaus.gmaven</groupId>
                <artifactId>gmaven-plugin</artifactId>
                <version>1.5</version>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-all</artifactId>
                        <scope>compile</scope>
                        <classifier>indy</classifier>
                        <version>2.4.5</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            
                            
                            <goal>compile</goal>
                            <goal>testCompile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

The point I'm making here is that this actually works, while if I change to gmavenplus-plugin I get the following error:

[INFO] Unable to get Groovy version from GroovySystem, trying InvokerHelper.
[WARNING] Unable to get Groovy version from InvokerHelper or GroovySystem, trying jar name.
[ERROR] Unable to determine Groovy version.  Is Groovy declared as a dependency?
[ERROR] Unable to determine Groovy version.  Is Groovy declared as a dependency?
[INFO] Unable to get Groovy version from GroovySystem, trying InvokerHelper.
[WARNING] Unable to get Groovy version from InvokerHelper or GroovySystem, trying jar name.
[ERROR] Unable to determine Groovy version.  Is Groovy declared as a dependency?

**Comment by keeganwitt** [comment]
GMaven bundles Groovy onto it's classpath to do compilation.  I made a design decision not to do that for various reasons (one of which was to avoid the unexpected behavior of a mistmatch between the version it was compiled with vs runtime version).  If you're going to do compilation, GMavenPlus requires Groovy to be a compile dependency of your project, not the plugin.
