### ISSUE TITLE
[RFC] pass system properties to script

### ISSUE THREAD

**Issue by missedone** [groovy/GMavenPlus#62]
hi folks

I'd like to pass some system properties to the groovy script, for now it looks like:
```xml
                <configuration>
                    <scripts>
                        <script>file:///${project.basedir}/src/test/groovy/Tester.groovy</script>
                    </scripts>
                </configuration>
```

i want something below:
```xml
                <configuration>
                   <systemProperties>
                      <foo>bar</foo>
                   </systemProperties>
                    <scripts>
                        <script>file:///${project.basedir}/src/test/groovy/Tester.groovy</script>
                    </scripts>
                </configuration>
```

so that in Tester.groovy, i can get the property with `System.getProperty('foo')`

thanks

**Comment by keeganwitt** [comment]
I think it'd be too late for me to try to add this in the plugin itself, because I don't fork the JVM process currently.  But you could do `mvn -Dfoo=bar gplus:execute`, and then access it with `System.getProperty('foo')` in your script.  That works today.

**Comment by missedone** [comment]
thanks for the workaround
however, i'd like to pass the maven properties (e.g. `project.version`, `project.basedir`) as system properties to groovy script. so it's not good fit to pass from mvn cli.

**Comment by keeganwitt** [comment]
Is there a reason it has to be with system properties rather than the bound properties as in the execute [example](https://github.com/groovy/GMavenPlus/wiki/Examples#execute-scripts)?

**Comment by missedone** [comment]
i'd like to keep the groovy script in a file rather than inlined in the pom.xml.
in this way, the bound properties not work anymore.

**Comment by keeganwitt** [comment]
You can use properties from a file.  Scripts are bound and executed the same regardless of source (file, URL, or POM).  If you've got an example that doesn't work, I'm happy to test it.

**Comment by missedone** [comment]
right, the bound properties available in the script file as well (but not in way of system properties)
i think it's better to highlight this on the example so that people can get this in the first read.
thanks
