### ISSUE TITLE
Wrong current working directory when running a script

### ISSUE THREAD

**Issue by gdemecki** [groovy/GMavenPlus#67]
Hi,

I have a maven java project with a two level hierarchy, one of the child modules uses the `gmavenplus-plugin` to execute some Groovy code, and among others, it's supposed to create a new file in the local directory with a `def newFile = new File("MY-NEW-FILE")` as follows:

```xml
<!-- child pom -->
<plugin>
  <groupId>org.codehaus.gmavenplus</groupId>
  <artifactId>gmavenplus-plugin</artifactId>
  <version>1.5</version>
  <executions>
    <execution>
      <configuration>
        <scripts>
          <script><![CDATA[
            def newFile = new File("MY-NEW-FILE")
            newFile.createNewFile()
            // ...

          ]]>
          </script>
        </scripts>
      </configuration>
      <goals>
        <goal>execute</goal>
      </goals>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.4.7</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</plugin>
```
But it turns out that when I run `mvn clean install` from the root `pom.xml`'s location, the file is unfortunately created at the root pom (although the child module executes the above script).

It seems to me not intuitive/ buggy. But what do you think?

Environment:
 * Oracle JDK "1.8.0_112" 64-Bit 
 * Apache Maven 3.2.5
 * OS Windows 7

BTW: This is not urgent, because fortunately workaround exists. I can pass the current directory explicitly:
```
def newFile = new File("$project.basedir", "MY-NEW-FILE")
```
---

But, can you please explain me one thing? When I surround a `project.basedir` variable with curly brackets, I'm getting:

```
[ERROR] Script1.groovy: 1: unexpected char: '\' @ line 1, column 31.
[ERROR] def newFile = new File("D:\dev\ws\parent-project\child-project", "MY-NEW-FILE")
```
It is of course related to the Windows and using backslashes in the paths which are special characters in Java. But shouldn't this case be handled gracefully by the Groovy plugin? Because IMHO this way Groovy scripts are not able to handle any Windows paths.
Should I create a separate bug for this? Or is this a known issue?

Kind regards,
Greg

**Comment by keeganwitt** [comment]
The backslash issue is because Groovy doesn't have a Windows-specific path string syntax, it must be doubly escaped just as you would in Java.  You'll notice the same behavior if you run that code in GroovyConsole.

[GroovyShell](http://docs.groovy-lang.org/latest/html/api/groovy/lang/GroovyShell.html) doesn't offer a way to set the working directory, I think because Java [doesn't](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=4045688) offer a mechanism to do that.

**Comment by gdemecki** [comment]
> The backslash issue is because Groovy doesn't have a Windows-specific path string syntax....

Can you show me how to work around this problem? I mean, how to deal with such strings?

> GroovyShell doesn't offer a way to set the working directory,

Ok, I understand this. The one thing that comes to my mind is, it's not very intuitive  because when I've used `gmavenplus-plugin` in the child module, I somehow assumed that a separate JVM was started there to execute my script. But it seems that Groovy just used the already started JVM, am I correct?

**Comment by keeganwitt** [comment]
Right, it's one JVM instance, not a separate one for each module.

I was talking about just escaping the string, like this `new File("C:\\some directory\\some file")`.

**Comment by gdemecki** [comment]
Thanks  Keegan.
I'm closing this issue .
