### ISSUE TITLE
question: how to execute external script from command line

### ISSUE THREAD

**Issue by sdmoralesma** [groovy/GMavenPlus#68]
Documentation is not clear about how to achieve something similar as in `gmaven`, where without any previous dependency/plugin configuration is possible to execute an external script:
`mvn org.codehaus.gmaven:groovy-maven-plugin:2.0:execute -Dsource=scripts/test.groovy`

I tried:
`mvn org.codehaus.gmavenplus:gmavenplus-plugin:1.5:execute -Dsource=scripts/test.groovy`

But throws exception:
`[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.5:execute (default-cli) on project example: The parameters 'scripts' for goal org.codehaus.gmavenplus:gmavenplus-plugin:1.5:execute are missing or invalid -> [Help 1]`

**Comment by keeganwitt** [comment]
There currently isn't a way execute a Groovy script without any configuration because GMavenPlus doesn't bundle Groovy into the plugin itself (to avoid class definition mismatches between the version the plugin was compiled with and the version you want to use with your project).  That's why GMaven had those runtime dependencies that were specified with provider configuration (with the hope that there'd be no breaking changes between patch versions of Groovy.  Occasionally, this wasn't the case, but the more problematic reason for my avoiding this approach was that the number of providers would need to double with the introduction of indy.

**Comment by rmannibucau** [comment]
Shouldn't this be supported?

    <plugin>
        <groupId>org.codehaus.gmavenplus</groupId>
        <artifactId>gmavenplus-plugin</artifactId>
        <version>1.6</version>
        <executions>
          <execution>
            <id>sc</id>
            <phase />
            <goals>
              <goal>execute</goal>
            </goals>
            <configuration>
              <scripts>
                <script>${project.basedir}/build/script/SomeScript.groovy</script>
              </scripts>
              <allowSystemExits>true</allowSystemExits>
            </configuration>
          </execution>
        </executions>
        <dependencies>
          <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.5.3</version>
          </dependency>
        </dependencies>
      </plugin>

is a valid configuration with groovy set properly but the plugin fails using 

    mvn gplus:execute@sc

**Comment by keeganwitt** [comment]
@rmannibucau That feature only works with Maven 3.3.1 or later: https://maven.apache.org/docs/3.3.1/release-notes.html.  I tested your POM on my machine with Maven 3.5.3 and it ran successfully.

**Comment by rmannibucau** [comment]
Failed for me on 3.5.4 saying scripts is not supported

**Comment by keeganwitt** [comment]
Clearly there's something different between our environments.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.github.keeganwitt</groupId>
    <artifactId>gmavenplus-test</artifactId>
    <version>1.0-SNAPSHOT</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.6.2</version>
                <executions>
                    <execution>
                        <id>exec</id>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                        <configuration>
                            <scripts>
                                <script><![CDATA[println "Hi!"]]></script>
                            </scripts>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-all</artifactId>
                        <version>2.5.3</version>
                        <type>pom</type>
                    </dependency>
                </dependencies>
            </plugin>
        </plugins>
    </build>
</project>
```
I tried it with 3.5.3
```
>mvn gplus:execute@exec
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.github.keeganwitt:gmavenplus-test >----------------
[INFO] Building gmavenplus-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- gmavenplus-plugin:1.6.2:execute (ex) @ gmavenplus-test ---
[INFO] Using Groovy 2.5.3 to perform execute.
Hi!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.401 s
[INFO] Finished at: 2018-11-04T22:50:41-05:00
[INFO] ------------------------------------------------------------------------

>mvn -version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T14:49:05-05:00)
Maven home: C:\bin\apache-maven-3.5.3\bin\..
Java version: 1.8.0_191, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jdk1.8.0_191\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
And with 3.6.0
```
>mvn gplus:execute@exec
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.github.keeganwitt:gmavenplus-test >----------------
[INFO] Building gmavenplus-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- gmavenplus-plugin:1.6.2:execute (exec) @ gmavenplus-test ---
[INFO] Using Groovy 2.5.3 to perform execute.
Hi!
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.440 s
[INFO] Finished at: 2018-11-04T22:55:27-05:00
[INFO] ------------------------------------------------------------------------

>mvn --version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: C:\bin\apache-maven-3.6.0\bin\..
Java version: 1.8.0_191, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_191\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by keeganwitt** [comment]
Do note, however, that if you specify the goal without the execution ID, it fails.  As far as I can tell, this is normal Maven behavior.  The scripts list is just a plain old Maven parameter, nothing special.

```
>mvn gplus:execute
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.github.keeganwitt:gmavenplus-test >----------------
[INFO] Building gmavenplus-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- gmavenplus-plugin:1.6.2:execute (default-cli) @ gmavenplus-test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.857 s
[INFO] Finished at: 2018-11-04T23:02:12-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6.2:execute (default-cli) on project gmavenplus-test: The parameters 'scripts' for goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6.2:execute are missing or invalid -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException
```

**Comment by rmannibucau** [comment]
I dont have a computer handy but wonder if that is my project structure: i want to execute the script for all modules so i defined it in the parent pom (packaging=pom is what can be different). Will try to check asap.

**Comment by rmannibucau** [comment]
@keeganwitt tried back in the project I had last week and was failing but can't reproduce it anymore so let's assume I did something wrong or our CI was in a dirty state leading to that issue. Sorry for the noise and thanks a lot for checking that fast.
