### ISSUE TITLE
GMavenPlus with Maven and Eclipse

### ISSUE THREAD

**Issue by mdelamere** [groovy/GMavenPlus#70]
Hi,

I am trying to get GMavenPlus working with maven and my eclipse. It seems to work for others who are using a different IDE, but I am unfortunately getting this error in eclipse:

> Plugin execution not covered by lifecycle configuration: org.codehaus.gmavenplus:gmavenplus-plugin:1.4:testCompile (execution: default, phase: test-compile)	pom.xml	/my-project	line 94	Maven Project Build Lifecycle Mapping Problem

Does this work for others or is there a general problem with this combination?

Thanks and best regards,
Michael

**Comment by missedone** [comment]
you can add it to eclipse m2e lifecycle mapping your pom.xml:

```xml
         <!--This plugin's configuration is for Eclipse m2e settings only. It has no influence on the Maven build itself.-->
        <plugin>
            <groupId>org.eclipse.m2e</groupId>
            <artifactId>lifecycle-mapping</artifactId>
            <version>1.0.0</version>
            <configuration>
                <lifecycleMappingMetadata>
                        <pluginExecution>
                            <pluginExecutionFilter>
                                <groupId>org.codehaus.gmavenplus</groupId>
                                <artifactId>gmavenplus-plugin</artifactId>
                                <versionRange>[0.0,)</versionRange>
                                <goals>
                                    <goal>execute</goal>
                                </goals>
                            </pluginExecutionFilter>
                            <action>
                                <execute>
                                    <runOnIncremental>true</runOnIncremental>
                                </execute>
                            </action>
                        </pluginExecution>
                    </pluginExecutions>
                </lifecycleMappingMetadata>
            </configuration>
        </plugin>
```

**Comment by keeganwitt** [comment]
I haven't heard anything more on this, so I'm assuming it's fine to close.

**Comment by hazendaz** [comment]
@mdelamere Do you have m2e installed for groovy in eclipse (http://dist.springsource.org/snapshot/GRECLIPSE/e4.7/)

**Comment by WolfgangFahl** [comment]
![grafik](https://user-images.githubusercontent.com/1336221/75092432-b5ee8b80-5577-11ea-8aec-79bc2e277678.png)

**Comment by jrichardsz** [comment]
@WolfgangFahl , in the eclipse 2021-12 there is an error after the installation that you suggested:

![image](https://user-images.githubusercontent.com/3322836/157109692-e576e286-40e1-408d-a846-730edc5ea08c.png)

Version: 2021-12 RC1 (4.22.0 RC1)
