### ISSUE TITLE
Spring Boot 1.4 jay layout change caused Spock tests cannot find classes while running using gmaven plus plugin

### ISSUE THREAD

**Issue by LeeU1911** [groovy/GMavenPlus#73]
Hi all,

Wondering if anyone run into the same issue. Our project has below structure:
```
parent
  |_spock-tests
  |_core-module
```
## Issue 
`spock-tests` can't find classes of core-module.

## Description
`spock-tests` consists a set of groovy specs which uses spock to do unit test and integration test of core-module functionalities. Hence, module spock-tests has a dependency on core-module jar file.

`core-module` is a Spring Boot app.

`mvn clean install` runs spock tests quite well until we upgraded `core-module` to use Spring Boot 1.5. We found out that in Spring Boot 1.4, the fat jar layout was changed to use conventional delegation model in LaunchedURLClassLoader as described [here](https://github.com/spring-projects/spring-boot/commit/87fe0b2adeef85c842c009bfeebac1c84af8a5d7).

This caused the jar file created of `core-modul`e has a different folder structure than it once was. The classes are moved to under `BOOT-INF` folder instead of being at the root of the jar file as before. We think this makes spock tests somehow doesn't 'see' those classes, therefore, throws the errors.

If you have any idea how to fix this, please help.

Thanks.

**Comment by keeganwitt** [comment]
No one else but me is gonna see things posted here, and lately I haven't used Maven terribly much in my day job to have a decent probability of seeing the same things you are.  I'd try asking on the user [mailing list](http://groovy-lang.org/mailing-lists.html), you might have more luck there.  This sounds like it might be a Spock issue, so I'm not sure how to help more at this point.  Can you reproduce this in a smaller project? I might be able to help narrow it down.

**Comment by LeeU1911** [comment]
Hi,

I appreciate your response. Didn't know that the mailing-list is more active than github issues. I already asked the Spock guys but they says it's not a Spock problem. Another proof is running the Spock tests from the IDE works fine. So I think their answer makes sense.

I'll try to reproduce this in a smaller project and will reply back. Thanks!

**Comment by keeganwitt** [comment]
Closing for now, as I haven't heard anything further.

**Comment by chzhyu** [comment]
I just ran into the same issue , and this

**Comment by chzhyu** [comment]
I Just run into the same issue, and this works for me.
https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#packaging.examples.local-artifact

**Comment by keeganwitt** [comment]
@LeeU1911 It's not more active, it's just another place to discuss use cases with other uses.

@chzhyu Thanks for sharing!
