### ISSUE TITLE
Stub compilation breaks with @AnnotationCollector

### ISSUE THREAD

**Issue by chrylis** [groovy/GMavenPlus#74]
I have a Groovy class annotated with an `@AnnotationCollector`, whose "annotation" class file, produced by the Groovy compiler, is actually an ordinary Java class. The stub generator leaves this `@CustomAnnotation` on the stub class, causing the Java compiler to fail because `CustomAnnotation` is not an annotation type:

```
[ERROR] /home/chrylis/project/target/generated-sources/groovy-stubs/main/com/example/Person.java:[10,40] incompatible types: com.example.annotation.CustomAnnotation cannot be converted to java.lang.annotation.Annotation
```

The correct approach here is probably either to drop `@AnnotationCollector` annotations entirely or to go ahead and unroll them for stubs (my suggestion).

**Comment by keeganwitt** [comment]
Unless I'm misunderstanding, you're suggesting a change to Groovy's compiler (GMavenPlus just calls Groovy's compilation classes, it doesn't control any of the compilation itself).  If so, I'd open a [Jira](https://issues.apache.org/jira/browse/GROOVY/) or ask on the [mailing list](http://groovy-lang.org/mailing-lists.html).

**Comment by chrylis** [comment]
Where does stub generation happen? The problem is that the stubs carry `@MyAnnotatedCollection`, which is not actually technically an annotation in the `.class` file.

**Comment by keeganwitt** [comment]
In Groovy, specifically most of the logic is in [JavaStubGenerator.java](https://github.com/apache/groovy/blob/master/src/main/org/codehaus/groovy/tools/javac/JavaStubGenerator.java).

**Comment by chrylis** [comment]
I can take a look, but I'll need sleep first. Essentially, though, an annotation that's actually an `@AnnotationCollector` can't be copied into Java source code without `javac` going nuts, because the corresponding class file isn't an annotation.

**Comment by keeganwitt** [comment]
I can help look too, I'm fairly familiar with that class.  Can you give a small example so I can make sure I'm looking at the same scenario?

**Comment by chrylis** [comment]
Sorry, this slipped off my radar. As an example, say we have a JPA class with a column named `myColumn`. The JPA `@Column` annotation has a permitted target of `{METHOD, FIELD}`. In Groovy, I can define an annotation collector called `SuperColumn` like this:

```
@AnnotationCollector
@Column(name = "placeholder")
@MoreAnnotations
@ExtraAnnotations
@interface SuperColumn {
}
```

When I then write this in my Groovy class:

```
@SuperColumn
String myColumn
```

then `groovyc` unrolls all of those annotations onto that field. However, from a technical standpoint in `SuperColumn.groovy` the `@Column` annotation is being applied to an illegal target. The generated stub looks like this:

```
@groovy.transform.AnnotationCollector()
@javax.persistence.Column(name="placeholder")
@my.MoreAnnotations
@my.ExtraAnnotations
public @interface SuperColumn
 {
;
}
```

and `javac` rejects it. The _most correct_ behavior in this whole non-compliant scenario is probably to strip all of the annotations that don't themselves have a target of `ANNOTATION`.

**Comment by chrylis** [comment]
Related: I have moved my collector annotations to a separate module, compiled as Groovy-only. Unfortunately, this only pushes the problem further down the pipeline. I have a collector annotation named `@SsoMainRecord`; this is compiled by Groovy into `@AnnotationCollector public final class SsoMainRecord implements GroovyObject`. In my main mixed project, I have this Groovy class:

```
@SsoMainRecord
class User {
}
```

which is stubbed as

```
@my.package.SsoMainRecord() public class User
  extends java.lang.Object  implements
    groovy.lang.GroovyObject { ...}
```

and then the stub fails to compile because `SsoMainRecord cannot be converted to java.lang.annotation.Annotation`.

**Comment by leonard84** [comment]
You don't even need a custom annotation `groovy.transform.CompileDynamic` has the same problem. I've created an issue [GROOVY-8814](https://issues.apache.org/jira/browse/GROOVY-8814).

**Comment by keeganwitt** [comment]
Thanks @leonard84.  I'm gonna close this, as there's an open issue against Groovy for this.
