### ISSUE TITLE
Groovy + Maven cant find JavaFx

### ISSUE THREAD

**Issue by nartz** [groovy/GMavenPlus#75]
Hi -

I am using Maven 3.3.9 + Spock Testing Framework + GMavenPlus (1.5) + Groovy 2.4 + JavaFX with Java8 on OSX 11.10. I'm trying to get `mvn test` to execute succesfully, but the groovy tests I have are not finding the javafx classes. The errors are like:

java.lang.ClassNotFoundException: javafx.scene.control.MenuBar

I believe the issue I'm having is due to java8 now by default includes the javafx jar on the classpath (/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/ext on OSX, which is below java home), it isn't an external dependency in maven. However, when running groovy with javafx, groovy doesn't seem to have the javafx jar on its path. 

Other projects like https://github.com/groovyfx-project/groovyfx seem to need groovy to specifically specify the jar on the command line using '-cp <path to javafx jar>'. Also, in gradle I found what I think is a similar bug: https://stackoverflow.com/questions/32570973/gradle-groovy-compilation-cannot-find-javafx-classes-in-tests.

Groovy seems to say that jars added in a ~/.groovy/lib folder will be added to the classpath, although putting the jfxrt.jar in there didn't seem to have an effect.

The main question is whats the best way to get groovy to find the javafx dependency jars so mvn test can succeed?

**Comment by keeganwitt** [comment]
Right now you have to make sure the Java you want to use is on the path first until I can implement #43, I haven't had as much free time this last year to take that on and it's not a small change :(

**Comment by keeganwitt** [comment]
Closing for now, as I don't know that there's anything further to fix here.
