### ISSUE TITLE
Compilation error when Compiling Traits with Generics

### ISSUE THREAD

**Issue by jlheard** [groovy/GMavenPlus#76]
I am receiving compilation errors when trying to compile classes using Maven that implement Traits with Generics.

I was able to compile without error using groovyc and IntelliJ make.

Here's some of my pom.
```xml
    <dependencies>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.5</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>addSources</goal>
                            <goal>addTestSources</goal>
                            <goal>generateStubs</goal>
                            <goal>compile</goal>
                            <goal>testGenerateStubs</goal>
                            <goal>testCompile</goal>
                            <goal>removeStubs</goal>
                            <goal>removeTestStubs</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        <plugins>
    </build>
```
```java
trait BaseService<T> {

     MongoRepository<T, String> mongoRepository

     public <T> List<T> findAll() {
        return mongoRepository.findAll()
     }
}
```
```java
class BaseServiceImpl implements BaseService<Domain> {

    @Autowired
    BaseServiceImpl(MyRepository myRespository) {
        this.mongoRepository = myRespository
    }

     // Do some stuff
}
```
Yielded: 

> [ERROR] BaseServiceImpl is not abstract and does not override abstract method setMongoRepository(org.springframework.data.mongodb.repository.MongoRepository<Domain,java.lang.String>) in BaseService

I was able to fix that compilation error by adding explicit getter and setter methods to the Trait as follows:
```java
trait BaseService<T> {

     MongoRepository<T, String> mongoRepository

     public <T> List<T> findAll() {
        return mongoRepository.findAll()
     }
    MongoRepository<T, String> setMongoRepository(MongoRepository<T, String> mongoRepository) {
        this.mongoRepository = mongoRepository
    }

    MongoRepository<T, String> getMongoRepository() {
        mongoRepository
    }
}
```
This then yielded the following compilation error which I am unable to resolve:

> [ERROR] BaseServiceImpl.java: cannot find symbol
[ERROR] symbol:   class T
[ERROR] location: class BaseServiceImpl

I have tried using Groovy 2.4.6, but that also did not work.  

To fix these errors when running ```mvn clean compile```, I made BaseService a regular class and had the implementing classes extend it, all of the compilation errors went away, and I was able to remove the explicit getter and setter.

It would be nice to use a Trait for this default logic if possible.

**Comment by keeganwitt** [comment]
It's happening because of the stubs (I'm not sure why yet). When I left the stub goals off, it compiled fine.

**Comment by jlheard** [comment]
OK, and thanks for looking into it for me.  I'll try to see if I'm able to deploy a build on our EC2 instance successfully without the stubs.

**Comment by keeganwitt** [comment]
The reason the stubs failed is the stub is missing the getter/setter you mentioned.  I'm thinking when you tried with groovyc, it must not have called javac against those stubs (otherwise it would have failed too).  I'm working on proving this theory.  Assuming that's the case, we'll want to raise this issue to get it fixed in Groovy.  GMavenPlus just calls the same code the Groovyc Ant task calls, so the fix would be in Groovy itself.

**Comment by jlheard** [comment]
Yes I searched the Internet for that and I saw a Stackoverflow article that stated they resolved a similar issue by upgrading to Groovy 2.4.6, and I tried that and I still got the error.  Let me try the latest version and I'll get back to you.

**Comment by jlheard** [comment]
I tried 2.4.11 and 2.5.0-beta-1 and still the same thing. I'll search their issue tracker and see if this is a known issue.

**Comment by keeganwitt** [comment]
FYI it happens even without the generics.  I created [GROOVY-8224](https://issues.apache.org/jira/browse/GROOVY-8224) for this issue and am working on a patch.

**Comment by keeganwitt** [comment]
I'm gonna close this issue, since it's a Groovy and not GMavenPlus issue.  The fix is a bit tricky, I haven't fixed it in Groovy yet.  Follow the Jira for further updates.

**Comment by MadeInChina** [comment]
+1
