### ISSUE TITLE
Possibility of accessing classloader for project dependencies within script

### ISSUE THREAD

**Issue by jimmoores** [groovy/GMavenPlus#82]
The [Reflections Maven Project](https://github.com/ronmamo/reflections-maven) suggests using GMavenPlus to scan project classes for Annotations, etc. at build time to speed up application start-up.  I have experimented with this and found it not obvious how (if possible?) to access the classpath of the project dependencies from within a script.  I noticed this was in issue #3 but closed without explanation.  Apologies if this is an old issue, I tried to go through the old issues and find commonalities.

I have opened an issue with the project in question, but this project seems a little more active so i was wondering if I might get a response here.  Happy to pitch in with a PR or wiki edit to document any solution...

**Comment by keeganwitt** [comment]
I honestly am drawing a blank on #3.  But the project's classpath is exposed to scripts executed with GMavenPlus (actually you can even use test dependencies), so it should work fine.  You'd just import the classes from dependencies you want to use, just as you would compiled Groovy.  For example,
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <dependencies>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.12</version>
            <classifier>indy</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.6</version>
        </dependency>
    </dependencies>
    <plugins>
        <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <scripts>
                        <script>
                            <![CDATA[
                                import org.apache.commons.lang3.StringUtils
                                println StringUtils.center("foobar", 80)
                            ]]></script>
                    </scripts>
                </configuration>
            </plugin>
        </plugins>
</project>
```
Also, you can declare dependencies in the plugin itself if they are not dependencies you have in the project but want to use.  Is this what you meant?

**Comment by jimmoores** [comment]
Thanks for the quick response. While I've continued working, I've realised
what I was wanting was a bit strange.

What I want are the classes that have been built so far (assuming we're
bound after the compile phase obviously) so I can scan them for annotations
and produce a metadata file for inclusion as a resource.

I've just found a workaround by converting the output directory into a URL
and scanning it directly rather than expecting it to be on any classpath.

Thanks again for taking the time to clarify the behaviour for me, I better
understand now.


On 10 Sep 2017 21:40, "Keegan Witt" <notifications@github.com> wrote:

I honestly am drawing a blank on #3
<https://github.com/groovy/GMavenPlus/issues/3>. But the project's
classpath is exposed to scripts executed with GMavenPlus (actually you can
even use test dependencies), so it should work fine. You'd just import the
classes from dependencies you want to use, just as you would compiled
Groovy. For example,

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <dependencies>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.12</version>
            <classifier>indy</classifier>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.6</version>
        </dependency>
    </dependencies>
    <plugins>
        <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <version>1.5</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <scripts>
                        <script>
                            <![CDATA[
                                import org.apache.commons.lang3.StringUtils
                                println StringUtils.center("foobar", 80)
                            ]]></script>
                    </scripts>
                </configuration>
            </plugin>
        </plugins>
</project>

Also, you can declare dependencies in the plugin itself if they are not
dependencies you have in the project but want to use. Is this what you
meant?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/groovy/GMavenPlus/issues/82#issuecomment-328370406>,
or mute
the thread

**Comment by keeganwitt** [comment]
Reading classes out of the target directory is probably the simplest way to do that anyway, at least that I can think of at the moment.
