### ISSUE TITLE
Trouble migrating from version 1.5 to version 1.6

### ISSUE THREAD

**Issue by pavgreen** [groovy/GMavenPlus#84]
We started getting the following error since we migrated to version 1.6
`
[ERROR] Could not find goal 'testCompile' in plugin org.codehaus.gmavenplus:gmavenplus-plugin:1.6 among available goals addSources, addStubSources, addTestSources, addTestStubSources, compile, compileTests, console, execute, generateStubs, generateTestStubs, groovydoc, groovydocTests, help, removeStubs, removeTestStubs, shell -> [Help 1]
`
Our pom configuration is as follows
```
<plugin>
  <groupId>org.codehaus.gmavenplus</groupId>
  <artifactId>gmavenplus-plugin</artifactId>
  <executions>
    <execution>
       <goals>
           <goal>compile</goal>
           <goal>testCompile</goal>
       </goals>
    </execution>
  </executions>
</plugin>
```
Tried replacing 'testCompile' with 'compileTests' but that resulted in the following error
`
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:compile (default) on project dingo: Execution default of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:compile failed. NullPointerException -> [Help 1]
`

Any ideas would be appreciated

**Comment by reftel** [comment]
I get the same error. In my case, I also get the following before the "BUILD FAILURE":

> [INFO] --- gmavenplus-plugin:1.6:compile (default) @ saksmappe-parent ---
> [INFO] Unable to get Groovy version from GroovySystem, trying InvokerHelper.
> [WARNING] Unable to get Groovy version from InvokerHelper or GroovySystem, trying jar name.
> [ERROR] Unable to determine Groovy version.  Is Groovy declared as a dependency?
> 

Do you also get that?

I've tried adding groovy-all as a direct dependency of the gmavenplus plugin inpluginManagement (in addition to listing it in dependencyManagement), but that did not help.

**Comment by keeganwitt** [comment]
@pavgreen what's the stacktrace please?

**Comment by keeganwitt** [comment]
@reftel Dependency versions are controlled with `dependencyManagement`, and plugin versions and configurations with `pluginManagement`, but just because it's in that section doesn't add the dependency to your project.  (Google "maven dependencyMangement vs dependencies").  If it's in a root, the children have to declare the dependency, which will use the version specified in `dependencyManagement`.  If you need to use it in the root project, but don't want to add it as a dependency there, you need to add to the plugin dependencies, like so
```xml
<plugin>
  <groupId>org.codehaus.gmavenplus</groupId>
  <artifactId>gmavenplus-plugin</artifactId>
  <version>1.6</version>
  <executions>
    <execution>
      <goals>
        <goal>addSources</goal>
        <goal>addTestSources</goal>
        <goal>generateStubs</goal>
        <goal>compile</goal>
        <goal>generateTestStubs</goal>
        <goal>compileTests</goal>
        <goal>removeStubs</goal>
        <goal>removeTestStubs</goal>
      </goals>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>org.codehaus.groovy</groupId>
      <artifactId>groovy-all</artifactId>
      <version>2.4.12</version>
      <scope>runtime</scope>
    </dependency>
  </dependencies>
</plugin>```

**Comment by pavgreen** [comment]
@keeganwitt please find the stacktrace below
```
13-Sep-2017 10:00:34	[ERROR] Could not find goal 'testCompile' in plugin org.codehaus.gmavenplus:gmavenplus-plugin:1.6 among available goals addSources, addStubSources, addTestSources, addTestStubSources, compile, compileTests, console, execute, generateStubs, generateTestStubs, groovydoc, groovydocTests, help, removeStubs, removeTestStubs, shell -> [Help 1]
13-Sep-2017 10:00:34	org.apache.maven.plugin.MojoNotFoundException: Could not find goal 'testCompile' in plugin org.codehaus.gmavenplus:gmavenplus-plugin:1.6 among available goals addSources, addStubSources, addTestSources, addTestStubSources, compile, compileTests, console, execute, generateStubs, generateTestStubs, groovydoc, groovydocTests, help, removeStubs, removeTestStubs, shell
13-Sep-2017 10:00:34	        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getMojoDescriptor(DefaultMavenPluginManager.java:275)
13-Sep-2017 10:00:34	        at org.apache.maven.plugin.DefaultBuildPluginManager.getMojoDescriptor(DefaultBuildPluginManager.java:239)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.DefaultLifecycleMappingDelegate.calculateLifecycleMappings(DefaultLifecycleMappingDelegate.java:110)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateLifecycleMappings(DefaultLifecycleExecutionPlanCalculator.java:248)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateMojoExecutions(DefaultLifecycleExecutionPlanCalculator.java:199)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:118)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.DefaultLifecycleExecutionPlanCalculator.calculateExecutionPlan(DefaultLifecycleExecutionPlanCalculator.java:135)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.builder.BuilderCommon.resolveBuildPlan(BuilderCommon.java:97)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:109)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:188)
13-Sep-2017 10:00:34	        at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:184)
13-Sep-2017 10:00:34	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13-Sep-2017 10:00:34	        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
13-Sep-2017 10:00:34	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
13-Sep-2017 10:00:34	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
13-Sep-2017 10:00:34	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
13-Sep-2017 10:00:34	        at java.lang.Thread.run(Thread.java:745)
```

**Comment by keeganwitt** [comment]
@pavgreen what was the stacktrace you got when replacing `testCompile` with `compileTests`? That rename is necessary in 1.6 because that's what I had to do to fix the issue with IntelliJ adding stubs as sources (they hard-coded the goal names the Groovy language support).

**Comment by reftel** [comment]
The stack trace I get (with compileTests, and with groovy as an explicit dependency on the gmavenplus plugin) is:

`	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:compile failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more
Caused by: java.lang.NullPointerException
	at org.codehaus.gmavenplus.util.ClassWrangler.getGroovyVersionString(ClassWrangler.java:158)
	at org.codehaus.gmavenplus.util.ClassWrangler.logGroovyVersion(ClassWrangler.java:298)
	at org.codehaus.gmavenplus.mojo.AbstractCompileMojo.doCompile(AbstractCompileMojo.java:169)
	at org.codehaus.gmavenplus.mojo.CompileMojo.execute(CompileMojo.java:63)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more`

The same pom file (except with testCompile as goal) works fine with version 1.5.

**Comment by keeganwitt** [comment]
Now that I think of it, I'm not sure I've ever run compilation goals with the dependencies declared in the plugin, only scripts.  This is because the compilation goals don't include the plugins dependencies to avoid polluting the compilation classpath with dependencies I used in the plugin.

When I run your minimal 1.5 example, I still get the NPE.  To make sure we're looking at the same thing, here's a complete example with 1.5: https://github.com/keeganwitt/gmavenplus-npe-test.

**Comment by pavgreen** [comment]
Thanks for posting the stacktrace @reftel, confirmed that I'm getting the same error

**Comment by reftel** [comment]
I also get the NPE on gmavenplus-npe-test, but not if I delete the src directory. With 1.6, if gets the NPE regardless of whether there is a src directory or not.
In the case I had where I reduced the pom to minimal-pom-xml.txt, there was no src directory.

**Comment by keeganwitt** [comment]
So the difference is I was logging the Groovy version after checking if there were no sources to compile (which would exit the mojo if there were not), whereas now I'm logging first before I check for there being sources.  The idea behind the change is I thought it'd be nice when running with debugging on to see what version of Groovy the plugin would use, even if it happens not to be doing any work at the moment.

It's easy to put it back, of course, but I'd like to understand your use case better to make sure we do the best fix we can for your use case.  Why are you invoking goals that need Groovy when you don't have Groovy as a dependency and there's no src?  Was this just copy/pasted into multiple POMs?

**Comment by reftel** [comment]
It was added to the parent pom by mistake, it seems. Removed it, and 'mvn install' now works. Thanks!

**Comment by keeganwitt** [comment]
@reftel Cool! Sorry the upgrade was a little rough.

@pavgreen Let me know if your situation is different.  If there's a use case I didn't consider, I definitely want to hear about it.

**Comment by reftel** [comment]
Well, the parent pom installs, but it turns out the invocation was not by mistake. All modules that use that parent pom now have to add the plugin invocatoin to their builds. Also, if the parent pom lists a goal that involves main sources in its pluginManagement and the module that uses it only has groovy test sources (we often write application code in Java and test code in Groovy), then the build crashes in the module. So, we more or less have to copy-paste the whole thing into every single module that uses the parent pom, insted of relying on the parent pom to set everything up, like we could in 1.5.

**Comment by keeganwitt** [comment]
Why not use `<pluginManagement>`? See my updated test https://github.com/keeganwitt/gmavenplus-npe-test

**Comment by pavgreen** [comment]
Thanks @keeganwitt, adding groovy as a dependency fixed the issue for me

**Comment by madorb** [comment]
Thanks for all the hard work on this! I do have one suggestion though... unless i'm missing it, there doesn't seem to be a ChangeLog - so when upgrading from 1.5 to 1.6 there is no clear way to know what to expect. I got bit by this same issue as well and generally i'd expect that breaking changes  like renaming goals etc. to show up in such a ChangeLog. Cheers, and thanks again for the work on this! http://keepachangelog.com/en/1.0.0/

**Comment by keeganwitt** [comment]
I summarize the changes in the email I send to the groovy users mailing list.  But I was thinking a couple weeks ago that I should add the notes to the Github releases page as well for the reasons you suggest (I don't know why I didn't think of that until now).  I'll do that going forward, and when I get some time I'll add at least the last couple releases as well since I should have notes for those.

**Comment by keeganwitt** [comment]
Another thing I've thought about doing several times is [semantic versioning](http://semver.org/).  That'd help make it clear when there's potentially breaking changes too.

**Comment by madorb** [comment]
Agreed! Semantic Versioning++++

**Comment by H3npi** [comment]
Hi all,

after reading this thread, i guess i ran into another issue with this:
i have the GMavenPlus plugin in my root pom specified in the pluginManagement section with Version 1.6:
```
<build>
        <pluginManagement>
            <plugins>
...
                 <plugin>
                    <groupId>org.codehaus.gmavenplus</groupId>
                    <artifactId>gmavenplus-plugin</artifactId>
                    <version>${version.plugin.gmavenplus}</version>
                </plugin>
...
            </plugins>
        </pluginManagement>
        <plugins>
...
        <!-- groovy compiler for compiling the Spock tests-->
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-and-compile-testsources</id>
                        <goals>
                            <goal>addTestSources</goal>
                            <goal>generateTestStubs</goal>
                            <goal>compileTests</goal>
                            <goal>removeTestStubs</goal>
                        </goals>
                    </execution>
                </executions>
                <!--tells the groovy compiler where to find the Spock test-->
                <configuration>
                    <testSources>
                        <testSource>
                            <directory>${project.basedir}/src/test/groovy</directory>
                            <includes>
                                <include>**/*.groovy</include>
                            </includes>
                        </testSource>
                    </testSources>
                </configuration>
            </plugin>
...
          </plugins>
```

Also i have declared the goorvy dependency in the dependencyManagement with the scope comile (Version 2.4.12)

```          
      <dependencyManagement>
         <dependencies>
...
            <dependency>
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy-all</artifactId>
                <version>${version.test.groovy}</version>
                <scope>compile</scope>
            </dependency>
... 
         </dependencyManagement>
       </dependencies>
```

So when i understand everything correct, this should work, but i still get the NPE
```
[ERROR] Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:generateTestStubs (add-and-compile-testsources) on project spapi: Execution add-and-compile-testsources of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:generateTestStubs failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:generateTestStubs (add-and-compile-testsources) on project spapi: Execution add-and-compile-testsources of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:generateTestStubs failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution add-and-compile-testsources of goal org.codehaus.gmavenplus:gmavenplus-plugin:1.6:generateTestStubs failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: java.lang.NullPointerException
        at org.codehaus.gmavenplus.util.ClassWrangler.getGroovyVersionString(ClassWrangler.java:158)
        at org.codehaus.gmavenplus.util.ClassWrangler.logGroovyVersion(ClassWrangler.java:298)
        at org.codehaus.gmavenplus.mojo.AbstractGenerateStubsMojo.doStubGeneration(AbstractGenerateStubsMojo.java:144)
        at org.codehaus.gmavenplus.mojo.GenerateTestStubsMojo.execute(GenerateTestStubsMojo.java:78)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        ... 21 more
```

And the logs:

```
[INFO] Unable to get Groovy version from GroovySystem, trying InvokerHelper.
[WARNING] Unable to get Groovy version from InvokerHelper or GroovySystem, trying jar name.
[ERROR] Unable to determine Groovy version.  Is Groovy declared as a dependency?
```

The NPE occures while compiling the root project, it doesn't even go into the child modules.
Any suggestions what i maybe have missed?

**Comment by keeganwitt** [comment]
If you are executing GMavenPlus goals in your root POM, you need to have Groovy in `<dependencies>` not `<dependencyManagement>`. `dependencyManagement` just sets the version and configuration for the children to use, it doesn't actually add the dependency to the build of the root.

**Comment by AnEmortalKid** [comment]
@H3npi mine worked with:

```xml
<dependencyManagement>
 <dependencies>
<dependency>
                <groupId>org.codehaus.groovy</groupId>
                <artifactId>groovy-all</artifactId>
                <version>${groovy-all.version}</version>
            </dependency>
</dependencies>
</dependencyManagement>

...

<dependencies>
<dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <scope>compile</scope>
        </dependency>
</dependencies>
```

**Comment by rusio** [comment]
> the notes to the Github releases page 

Any chance we get written release notes?

It would remove some doubts when migrating from 1.5 to 1.6 ...

**Comment by keeganwitt** [comment]
Sorry for the delay, I'll try to get to that this weekend.

**Comment by keeganwitt** [comment]
I'll go through the commits and make sure I didn't miss anything (especially for older releases).  But I've got the notes up now (going back to 1.0): https://github.com/groovy/GMavenPlus/releases.

**Comment by lostiniceland** [comment]
The 1.6 release is pretty painful for us. As @reftel we only use Groovy for testing (Spock), and now I have to make sure that I apply the plugin to the modules which have a groovy-test-source. If I forget one, no tests will run which might break things. The projects consists of 50+ modules (yes we need to clean this up). Adding it to the wrong module will result in the menitioned NPE.

I prefer plugins which I only have to configure once and they figure out by themselves if they have to do something within the child-modules. Maybe this could be added in a coming release.

**Comment by keeganwitt** [comment]
@lostiniceland So to be clear -- this was because if you added the plugin to a module without any Groovy sources, it's a problem, so you had to add to each individually, and are worried about missing one?

**Comment by lostiniceland** [comment]
Yes. We are dealing with a huge legacy app where we introduce Spock testing incrementally, so the groovy-modules are scattered around the codebase depending on the work within the last year.

In my opinion the solution from 1.5 was nice, because you've set the groovy-runtime for the plugin directly withing the plugins definition. The explicit dependency from 1.6 has another side effect as I found out yesterday:
Since we only use groovy for testing I have to make sure to not silently ship groovy with our application. After making sure all groovy-deps have a test-scope the plugin crashed again with a NPE.
As it turned out, it depends on the configured goal. I also had the compile-goal in my plugin-config which again was looking for a groovy runtime and couldnt find one (in compile scope).
So for our setup we must only use addSources/addTestSources/compileTests.

**Comment by keeganwitt** [comment]
That makes sense.  I apologize for the inconvenience.  That change was meant just to make the log ordering consistent between goals, I didn't intend to cause the mess that I did. I'll try to get a fix out this weekend.

**Comment by keeganwitt** [comment]
Just to be extra sure, could you verify 1.6.1-SNAPSHOT from https://oss.sonatype.org/content/groups/staging/ resolves your issue?

**Comment by lostiniceland** [comment]
I will give it a test on Wednesday. Sorry for the delay...and thanks for the quick resolution

**Comment by keeganwitt** [comment]
@lostiniceland That hasn't been there since probably 1.1 and older.  Here was my concern with bringing that back: If I mix the plugin and project classpaths than _all_ dependencies of GMavenPlus will be on your classpath.  That means it could compile against the plugins version of a dependency instead of the version specified in your project.  This could lead to issues at runtime.

**Comment by keeganwitt** [comment]
@lostiniceland Actually -- I don't need a separate configurator, I just need to change the ClassWrangler constructor arg.  I don't think this is a good practice; if your project uses Groovy, it should depend on Groovy.  But a couple people have asked for this, and I've generally taken the approach of giving the user as much ammo as they want to shoot themselves in the foot, so I guess I'll add this as an opt-in option.

**Comment by keeganwitt** [comment]
#86 is the issue to track using Groovy as a plugin dependency FYI.

**Comment by duongvu89** [comment]
I fixed the issue by removing the codehaus folder in .m2 folder!

**Comment by LhhhL** [comment]
> I fixed the issue by removing the codehaus folder in .m2 folder!

It's very useful, thx!
