### ISSUE TITLE
incompatible types generated when using Java generics

### ISSUE THREAD

**Issue by szantopeter** [groovy/GMavenPlus#90]
I have a groovy class
    
    class AnimalBuilder<T extends Animal>

and a sub class

    class CatBuilder extends AnimalBuilder<Cat> {

and java domain objects

    public abstract class Animal {

and

    public class Cat extends Animal {

when compiling I get the below error 

[ERROR] /C:/dev/src/groovy-compile-failure/target/generated-sources/groovy-stubs/main/org/example/CatBuilder.java:[16,8] incompatible types: org.example.domain.Animal cannot be converted to org.example.domain.Cat

The full code example can be found here https://github.com/szantopeter/groovy-compile-failure

**Comment by keeganwitt** [comment]
I'm not sure yet why the compiler doesn't see the Java objects on the classpath.  As a workaround, you could do this
```xml
<configuration>
  <sources>
    <source>
      <directory>${project.basedir}/src/main/groovy</directory>
      <includes>
        <include>**/*.groovy</include>
      </includes>
    </source>
    <source>
      <directory>${project.basedir}/src/main/java</directory>
      <includes>
        <include>**/*.java</include>
      </includes>
    </source>
  </sources>
</configuration>
```

I'm still looking into this.  Thank you for the example.

**Comment by keeganwitt** [comment]
Research notes: GMaven and Groovyc via AntRun both have the same failure.

**Comment by szantopeter** [comment]
in this case maybe the problem is in the compiler itself? If that is the case I will open a bug in the groovy jira

**Comment by keeganwitt** [comment]
It is the Groovy's compilation classes, yes.  I believe 7306 is already opened against this problem.

**Comment by keeganwitt** [comment]
Closing, as there's an open issue against Groovy for this.
