### ISSUE TITLE
Incorrect version checking in 1.6

### ISSUE THREAD

**Issue by jkubrynski** [groovy/GMavenPlus#93]
Requested to use configScript, but your Groovy version (2.4.12) doesn't support it (must be 2.1.0-beta-1 or newer).  Ignoring configScript parameter.

**Comment by keeganwitt** [comment]
You know what it probably is?  I just realized I have a bug in my logging -- if the config file doesn't exist, it also logs as version not supported.

**Comment by jkubrynski** [comment]
True - I've just checked it

**Comment by keeganwitt** [comment]
I'll fix the log message in the next release.
