### ISSUE TITLE
`groovy-all` required as `compile` since 1.6

### ISSUE THREAD

**Issue by abelsromero** [groovy/GMavenPlus#95]
After upgrading to 1.6 and updating the goals I get the message:
```
[INFO] --- gmavenplus-plugin:1.6:compile (default) @ ---
[INFO] Unable to get Groovy version from GroovySystem, trying InvokerHelper.
[WARNING] Unable to get Groovy version from InvokerHelper or GroovySystem, trying jar name.
[ERROR] Unable to determine Groovy version.  Is Groovy declared as a dependency?
```

Checking other issues I saw that the build works if I set `groovy-all` to scope compile, but in my case I only use groovy for testing, so I only need it test scope.
Adding groovy as dependency to the plugin does not fix it either.

**Comment by keeganwitt** [comment]
Please share you pom, it should work fine to use Groovy as a test scope.

**Comment by abelsromero** [comment]
Thanks a lot, I found it while building a demo project!
I was running the script in a `pom` module and `groovy-all` was set in the `dependencyManagement` section. Adding the dependency to a `dependencies` section at project or plugin level worked fine.
