### ISSUE TITLE
Memory leak in integration tests since 1.5 version

### ISSUE THREAD

**Issue by wilddziki** [groovy/GMavenPlus#97]
I am using this plugin quite long time but recently I upgraded it from 1.4 to 1.6 version. Unfortunately it started consuming a lot of memory when I am launching integration tests. This causing a lot of problems especially when couple of build is simultaneously launched on Jenkins environment. Linux machine just killing the processes.

It seems that the memory is not recycled at all between tests and everything is kept in memory during whole maven build.
Here is the chart of metaspace when 1.6 is used, it usually consumes at the end of my tests (not visible on this chart) even 1GB:

![gmavenplus-memory-leak](https://user-images.githubusercontent.com/7023247/39855749-7d553e2e-542d-11e8-8de8-2f841485996c.jpg)

With 1.4 version it takes only 175MB and recycles memory properly, here is the memory chart:

![gmavenplus-memory-leak-proper](https://user-images.githubusercontent.com/7023247/39855788-a2a46d44-542d-11e8-972d-c35029de810d.jpg)

I am using:
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Java version: 1.8.0_161, vendor: Oracle Corporation

```xml
            <plugin>
		<groupId>org.codehaus.gmavenplus</groupId>
        	<artifactId>gmavenplus-plugin</artifactId>
        	<version>1.6</version><executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                            <goal>compileTests</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.codehaus.groovy</groupId>
                        <artifactId>groovy-all</artifactId>
                        <version>2.4.14</version>
                        <scope>runtime</scope>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by keeganwitt** [comment]
Hmm... I'll take a look.  I can't recall anything that changed in 1.6 that would have changed the memory characteristics. though  To be clear: is this happening during test compilation? Or test execution?  And is there anything distinctive about your project (high number of classes, big classes) I should focus on testing?

**Comment by keeganwitt** [comment]
I used this POM to profile compiling 50k classes. I get totally different performance.
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.keeganwitt</groupId>
    <artifactId>gmavenplus-perf-test</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>GMavenPlus Performance Test</name>

    <dependencies>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>2.4.15</version>
            <classifier>indy</classifier>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.gmavenplus</groupId>
                <artifactId>gmavenplus-plugin</artifactId>
                 <!--<version>1.5</version>-->
                 <version>1.6</version>
                <executions>
                    <execution>
                        <id>generate-sources</id>
                        <goals>
                            <goal>execute</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                        <scripts>
                            <script><![CDATA[
                                def srcDir = new File(project.build.directory, "/generated-sources/src/main/groovy")
                                srcDir.mkdirs()
                                for (i in 1..50_000) {
                                    new File(srcDir, "_${i}.groovy").text = "class _${i} { }"
                                }
                            ]]></script>
                        </scripts>
                        </configuration>
                    </execution>
                    <execution>
                        <id>build</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                        <configuration>
                            <sources>
                             <source>
                                <directory>${project.build.directory}/generated-sources/src/main/groovy</directory>
                                <includes>
                                    <include>**/*.groovy</include>
                                </includes>
                                </source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```
![image](https://user-images.githubusercontent.com/64612/39905048-5373e692-54a9-11e8-99a7-6f0a0d144f68.png)

**Comment by keeganwitt** [comment]
Do you have any suggestions on how I can reproduce this?  Is there anything particularly distinctive about your project (a lot of modules, some kind of embedded processes in your integration tests, etc)?

**Comment by keeganwitt** [comment]
Closing for now, as I haven't heard back.

**Comment by wilddziki** [comment]
Hello,
sorry for late update!
It seems that from 1.6.2 all works perfectly fine, I did not have time to investigate the issue so choose the simplest way of solving my problem, downgrading it to 1.4 :)
Now I have upgraded it to 1.6.2 and memory looks fine.
