### ISSUE TITLE
Include value of targetBytecode in exception message

### ISSUE THREAD

**Issue by chrylis** [groovy/GMavenPlus#98]
If `targetBytecode` is not set to a value that GMavenPlus recognizes, then an `IllegalArgumentException` is thrown when the mojo is run. It can be tricky to figure out exactly where this is applied, and it would be helpful if the exception message indicated what the resolved value actually is (whether null or something else entirely).

https://github.com/groovy/GMavenPlus/blob/ef3a3d51dae4d13ab12821e679d594a8bf468179/src/main/java/org/codehaus/gmavenplus/mojo/AbstractCompileMojo.java#L329

**Comment by keeganwitt** [comment]
Fair point.  This is fixed in 681d3289df117e554099b4e12fa239ce6d5f2330.
