### ISSUE TITLE
1.6.1 missing from maven central

### ISSUE THREAD

**Issue by zman0900** [groovy/GMavenPlus#99]
1.6 appears to be the latest available version in maven central, but 1.6.1 has been tagged here for a month.

**Comment by keeganwitt** [comment]
Thanks for reporting this.  I don't see it in Sonatype OSS repo either, which is where I stage it to get into Central.  I could have sworn I released it there, but it seems to be gone now.  GPG is giving me problems, but I'll work on getting it uploaded.

**Comment by keeganwitt** [comment]
It's available in Sonatype OSS now, and should be synced to Central shortly.
https://oss.sonatype.org/content/repositories/releases/org/codehaus/gmavenplus/gmavenplus-plugin/1.6.1/
